// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Share struct {
	ID           int64              `json:"id"`
	SessionID    string             `json:"session_id"`
	PartyID      string             `json:"party_id"`
	PublicKey    string             `json:"public_key"`
	Address      string             `json:"address"`
	ShareData    []byte             `json:"share_data"`
	Threshold    int32              `json:"threshold"`
	TotalParties int32              `json:"total_parties"`
	PartyIndex   int32              `json:"party_index"`
	Curve        string             `json:"curve"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
