// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CountSharesByPartyID(ctx context.Context, partyID string) (int64, error)
	CreateShare(ctx context.Context, arg CreateShareParams) (Share, error)
	DeleteShare(ctx context.Context, id int64) error
	DeleteShareBySessionAndParty(ctx context.Context, arg DeleteShareBySessionAndPartyParams) error
	GetShareByID(ctx context.Context, id int64) (Share, error)
	GetShareBySessionAndParty(ctx context.Context, arg GetShareBySessionAndPartyParams) (Share, error)
	GetSharesByAddress(ctx context.Context, address string) ([]Share, error)
	GetSharesByPartyID(ctx context.Context, partyID string) ([]Share, error)
	GetSharesByPublicKey(ctx context.Context, publicKey string) ([]Share, error)
	ListShares(ctx context.Context, arg ListSharesParams) ([]Share, error)
	ShareExists(ctx context.Context, arg ShareExistsParams) (bool, error)
	UpdateShareData(ctx context.Context, arg UpdateShareDataParams) (Share, error)
}

var _ Querier = (*Queries)(nil)
