// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: shares.sql

package db

import (
	"context"
)

const countSharesByPartyID = `-- name: CountSharesByPartyID :one
SELECT COUNT(*) FROM shares
WHERE party_id = $1
`

func (q *Queries) CountSharesByPartyID(ctx context.Context, partyID string) (int64, error) {
	row := q.db.QueryRow(ctx, countSharesByPartyID, partyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createShare = `-- name: CreateShare :one
INSERT INTO shares (
    session_id,
    party_id,
    public_key,
    address,
    share_data,
    threshold,
    total_parties,
    party_index,
    curve
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9
)
RETURNING id, session_id, party_id, public_key, address, share_data, threshold, total_parties, party_index, curve, created_at, updated_at
`

type CreateShareParams struct {
	SessionID    string `json:"session_id"`
	PartyID      string `json:"party_id"`
	PublicKey    string `json:"public_key"`
	Address      string `json:"address"`
	ShareData    []byte `json:"share_data"`
	Threshold    int32  `json:"threshold"`
	TotalParties int32  `json:"total_parties"`
	PartyIndex   int32  `json:"party_index"`
	Curve        string `json:"curve"`
}

func (q *Queries) CreateShare(ctx context.Context, arg CreateShareParams) (Share, error) {
	row := q.db.QueryRow(ctx, createShare,
		arg.SessionID,
		arg.PartyID,
		arg.PublicKey,
		arg.Address,
		arg.ShareData,
		arg.Threshold,
		arg.TotalParties,
		arg.PartyIndex,
		arg.Curve,
	)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PartyID,
		&i.PublicKey,
		&i.Address,
		&i.ShareData,
		&i.Threshold,
		&i.TotalParties,
		&i.PartyIndex,
		&i.Curve,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteShare = `-- name: DeleteShare :exec
DELETE FROM shares
WHERE id = $1
`

func (q *Queries) DeleteShare(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteShare, id)
	return err
}

const deleteShareBySessionAndParty = `-- name: DeleteShareBySessionAndParty :exec
DELETE FROM shares
WHERE session_id = $1 AND party_id = $2
`

type DeleteShareBySessionAndPartyParams struct {
	SessionID string `json:"session_id"`
	PartyID   string `json:"party_id"`
}

func (q *Queries) DeleteShareBySessionAndParty(ctx context.Context, arg DeleteShareBySessionAndPartyParams) error {
	_, err := q.db.Exec(ctx, deleteShareBySessionAndParty, arg.SessionID, arg.PartyID)
	return err
}

const getShareByID = `-- name: GetShareByID :one
SELECT id, session_id, party_id, public_key, address, share_data, threshold, total_parties, party_index, curve, created_at, updated_at FROM shares
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetShareByID(ctx context.Context, id int64) (Share, error) {
	row := q.db.QueryRow(ctx, getShareByID, id)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PartyID,
		&i.PublicKey,
		&i.Address,
		&i.ShareData,
		&i.Threshold,
		&i.TotalParties,
		&i.PartyIndex,
		&i.Curve,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getShareBySessionAndParty = `-- name: GetShareBySessionAndParty :one
SELECT id, session_id, party_id, public_key, address, share_data, threshold, total_parties, party_index, curve, created_at, updated_at FROM shares
WHERE session_id = $1 AND party_id = $2
LIMIT 1
`

type GetShareBySessionAndPartyParams struct {
	SessionID string `json:"session_id"`
	PartyID   string `json:"party_id"`
}

func (q *Queries) GetShareBySessionAndParty(ctx context.Context, arg GetShareBySessionAndPartyParams) (Share, error) {
	row := q.db.QueryRow(ctx, getShareBySessionAndParty, arg.SessionID, arg.PartyID)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PartyID,
		&i.PublicKey,
		&i.Address,
		&i.ShareData,
		&i.Threshold,
		&i.TotalParties,
		&i.PartyIndex,
		&i.Curve,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSharesByAddress = `-- name: GetSharesByAddress :many
SELECT id, session_id, party_id, public_key, address, share_data, threshold, total_parties, party_index, curve, created_at, updated_at FROM shares
WHERE address = $1
ORDER BY created_at DESC
`

func (q *Queries) GetSharesByAddress(ctx context.Context, address string) ([]Share, error) {
	rows, err := q.db.Query(ctx, getSharesByAddress, address)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Share{}
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PartyID,
			&i.PublicKey,
			&i.Address,
			&i.ShareData,
			&i.Threshold,
			&i.TotalParties,
			&i.PartyIndex,
			&i.Curve,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharesByPartyID = `-- name: GetSharesByPartyID :many
SELECT id, session_id, party_id, public_key, address, share_data, threshold, total_parties, party_index, curve, created_at, updated_at FROM shares
WHERE party_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetSharesByPartyID(ctx context.Context, partyID string) ([]Share, error) {
	rows, err := q.db.Query(ctx, getSharesByPartyID, partyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Share{}
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PartyID,
			&i.PublicKey,
			&i.Address,
			&i.ShareData,
			&i.Threshold,
			&i.TotalParties,
			&i.PartyIndex,
			&i.Curve,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSharesByPublicKey = `-- name: GetSharesByPublicKey :many
SELECT id, session_id, party_id, public_key, address, share_data, threshold, total_parties, party_index, curve, created_at, updated_at FROM shares
WHERE public_key = $1
ORDER BY created_at DESC
`

func (q *Queries) GetSharesByPublicKey(ctx context.Context, publicKey string) ([]Share, error) {
	rows, err := q.db.Query(ctx, getSharesByPublicKey, publicKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Share{}
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PartyID,
			&i.PublicKey,
			&i.Address,
			&i.ShareData,
			&i.Threshold,
			&i.TotalParties,
			&i.PartyIndex,
			&i.Curve,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShares = `-- name: ListShares :many
SELECT id, session_id, party_id, public_key, address, share_data, threshold, total_parties, party_index, curve, created_at, updated_at FROM shares
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type ListSharesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListShares(ctx context.Context, arg ListSharesParams) ([]Share, error) {
	rows, err := q.db.Query(ctx, listShares, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Share{}
	for rows.Next() {
		var i Share
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.PartyID,
			&i.PublicKey,
			&i.Address,
			&i.ShareData,
			&i.Threshold,
			&i.TotalParties,
			&i.PartyIndex,
			&i.Curve,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const shareExists = `-- name: ShareExists :one
SELECT EXISTS(
    SELECT 1 FROM shares
    WHERE session_id = $1 AND party_id = $2
)
`

type ShareExistsParams struct {
	SessionID string `json:"session_id"`
	PartyID   string `json:"party_id"`
}

func (q *Queries) ShareExists(ctx context.Context, arg ShareExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, shareExists, arg.SessionID, arg.PartyID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const updateShareData = `-- name: UpdateShareData :one
UPDATE shares
SET share_data = $1
WHERE id = $2
RETURNING id, session_id, party_id, public_key, address, share_data, threshold, total_parties, party_index, curve, created_at, updated_at
`

type UpdateShareDataParams struct {
	ShareData []byte `json:"share_data"`
	ID        int64  `json:"id"`
}

func (q *Queries) UpdateShareData(ctx context.Context, arg UpdateShareDataParams) (Share, error) {
	row := q.db.QueryRow(ctx, updateShareData, arg.ShareData, arg.ID)
	var i Share
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.PartyID,
		&i.PublicKey,
		&i.Address,
		&i.ShareData,
		&i.Threshold,
		&i.TotalParties,
		&i.PartyIndex,
		&i.Curve,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
