package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"log"

	"github.com/mpc_hsm/gqlgen-todos/graph/model"
	"github.com/mpc_hsm/gqlgen-todos/tss"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*model.Todo, error) {
	panic(fmt.Errorf("not implemented: CreateTodo - createTodo"))
}

// GenerateDistributedKey is the resolver for the generateDistributedKey field.
func (r *mutationResolver) GenerateDistributedKey(ctx context.Context, input model.KeygenInput) (*model.KeygenResult, error) {
	log.Printf("Starting distributed key generation: threshold=%d, totalParties=%d", input.Threshold, input.TotalParties)

	// Create keygen coordinator
	coordinator, err := tss.NewKeygenCoordinator(int(input.Threshold), int(input.TotalParties))
	if err != nil {
		return &model.KeygenResult{
			Success: false,
			Message: fmt.Sprintf("Failed to create coordinator: %v", err),
		}, nil
	}

	// Generate pre-parameters (offline phase)
	log.Println("Generating pre-parameters...")
	if err := coordinator.GeneratePreParams(); err != nil {
		return &model.KeygenResult{
			Success: false,
			Message: fmt.Sprintf("Failed to generate pre-params: %v", err),
		}, nil
	}

	// Initialize all parties
	log.Println("Initializing parties...")
	if err := coordinator.InitializeParties(); err != nil {
		return &model.KeygenResult{
			Success: false,
			Message: fmt.Sprintf("Failed to initialize parties: %v", err),
		}, nil
	}

	// Run the keygen protocol
	log.Println("Running keygen protocol...")
	tssResult, err := coordinator.RunKeygen()
	if err != nil {
		log.Printf("Keygen failed: %v", err)
		return &model.KeygenResult{
			Success: false,
			Message: fmt.Sprintf("Keygen failed: %v", err),
		}, nil
	}

	// Verify shares
	log.Println("Verifying shares...")
	if err := coordinator.VerifyShares(); err != nil {
		log.Printf("Share verification warning: %v", err)
	}

	// Convert TSS shares to GraphQL model
	shares := make([]*model.PartyShare, len(tssResult.Shares))
	for i, share := range tssResult.Shares {
		shares[i] = &model.PartyShare{
			PartyID:    share.PartyID,
			ShareID:    share.ShareID,
			ShareValue: share.ShareValue,
		}
	}

	// Convert TSS result to GraphQL model
	result := &model.KeygenResult{
		PublicKey:   tssResult.PublicKey,
		PrivateKey:  tssResult.PrivateKey,
		Address:     tssResult.Address,
		PartyIds:    tssResult.PartyIDs,
		Shares:      shares,
		Threshold:   tssResult.Threshold,
		TotalShares: tssResult.TotalShares,
		Success:     tssResult.Success,
		Message:     tssResult.Message,
	}

	log.Printf("Keygen completed successfully! Public key: %s, Private key: %s, Address: %s", result.PublicKey, result.PrivateKey, result.Address)
	log.Printf("Generated %d shares for parties", len(result.Shares))
	return result, nil
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*model.Todo, error) {
	panic(fmt.Errorf("not implemented: Todos - todos"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
