package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"log"
	"time"

	pb "github.com/mpc_hsm/node/proto"
	"github.com/mpc_hsm/orchestrator/graph/model"
)

// RegisterNode - резолвер для регистрации новой ноды.
// Подключается к ноде по gRPC и получает её информацию.
func (r *mutationResolver) RegisterNode(ctx context.Context, input model.RegisterNodeInput) (*model.Node, error) {
	// Подключаемся к ноде через gRPC
	client, err := r.NodeManager.AddNode(ctx, input.Address)
	if err != nil {
		return nil, fmt.Errorf("не удалось подключиться к ноде %s: %w", input.Address, err)
	}

	// Получаем информацию о ноде
	info, err := client.GetNodeInfo(ctx)
	if err != nil {
		return nil, fmt.Errorf("не удалось получить информацию о ноде: %w", err)
	}

	r.mu.Lock()
	defer r.mu.Unlock()

	r.nodeCounter++
	id := fmt.Sprintf("node_%d", r.nodeCounter)

	// Используем данные от ноды, если не переданы явно
	partyID := input.PartyID
	if partyID == "" {
		partyID = info.PartyId
	}

	publicKey := input.PublicKey
	if publicKey == "" {
		publicKey = info.PublicKey
	}

	node := &model.Node{
		ID:        id,
		PartyID:   partyID,
		Address:   input.Address,
		PublicKey: publicKey,
		Status:    model.NodeStatusOnline,
		LastSeen:  time.Now().UTC().Format(time.RFC3339),
	}

	r.nodes[id] = node

	log.Printf("Нода зарегистрирована: %s (party: %s, address: %s)", id, partyID, input.Address)

	return node, nil
}

// DeleteNode is the resolver for the deleteNode field.
func (r *mutationResolver) DeleteNode(ctx context.Context, id string) (*model.Node, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	// Проверяем, существует ли нода в локальном хранилище
	node, exists := r.nodes[id]
	if !exists {
		return nil, fmt.Errorf("нода %s не найдена", id)
	}

	// Удаляем из NodeManager по partyID
	if err := r.NodeManager.RemoveNode(node.PartyID); err != nil {
		log.Printf("Предупреждение: не удалось удалить ноду из NodeManager: %v", err)
	}

	// Удаляем из локального хранилища
	delete(r.nodes, id)

	node.Status = model.NodeStatusOffline
	return node, nil
}

// CreateSession - резолвер для создания новой MPC сессии.
func (r *mutationResolver) CreateSession(ctx context.Context, input model.CreateSessionInput) (*model.Session, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	r.sessionCounter++
	id := fmt.Sprintf("session_%d", r.sessionCounter)

	session := &model.Session{
		ID:           id,
		Type:         input.Type,
		Status:       model.SessionStatusPending,
		Participants: input.Participants,
		Threshold:    input.Threshold,
		CreatedAt:    time.Now().UTC().Format(time.RFC3339),
	}

	r.sessions[id] = session

	log.Printf("Сессия создана: %s (type: %s, participants: %v)", id, input.Type, input.Participants)

	return session, nil
}

// StartKeygen - резолвер для запуска распределённой генерации ключей (DKG).
// Координирует keygen между всеми участвующими MPC нодами.
func (r *mutationResolver) StartKeygen(ctx context.Context, input model.StartKeygenInput) (*model.KeygenResult, error) {
	// Определяем участников
	var participants []string
	if len(input.Participants) > 0 {
		participants = input.Participants
	} else {
		// Используем все зарегистрированные ноды
		r.mu.RLock()
		for _, node := range r.nodes {
			participants = append(participants, node.PartyID)
		}
		r.mu.RUnlock()
	}

	if len(participants) < 2 {
		return nil, fmt.Errorf("требуется минимум 2 участника для keygen, получено: %d", len(participants))
	}

	if int(input.Threshold) > len(participants) {
		return nil, fmt.Errorf("threshold (%d) не может быть больше количества участников (%d)", input.Threshold, len(participants))
	}

	if input.Threshold < 1 {
		return nil, fmt.Errorf("threshold должен быть >= 1")
	}

	// Определяем кривую
	curve := "secp256k1"
	if input.Curve != nil && *input.Curve != "" {
		curve = *input.Curve
	}

	// Генерируем ID сессии
	r.mu.Lock()
	r.sessionCounter++
	sessionID := fmt.Sprintf("keygen_%d", r.sessionCounter)
	r.mu.Unlock()

	log.Printf("Запуск keygen сессии %s: participants=%v, threshold=%d, curve=%s",
		sessionID, participants, input.Threshold, curve)

	// Получаем клиентов для всех участников
	clients, err := r.NodeManager.GetNodesByPartyIDs(participants)
	if err != nil {
		return nil, fmt.Errorf("не удалось получить ноды: %w", err)
	}

	// Формируем информацию о участниках
	parties := make([]*pb.PartyInfo, len(participants))
	for i, partyID := range participants {
		client, _ := r.NodeManager.GetNode(partyID)
		parties[i] = &pb.PartyInfo{
			PartyId:    partyID,
			PartyIndex: int32(i),
			Address:    client.GetAddress(),
		}
	}

	// Инициализируем keygen на всех нодах
	for _, client := range clients {
		if err := client.InitKeygen(ctx, sessionID, parties, input.Threshold, curve); err != nil {
			return nil, fmt.Errorf("не удалось инициализировать keygen на ноде %s: %w", client.GetPartyID(), err)
		}
	}

	log.Printf("Keygen инициализирован на всех нодах, начинаем обмен сообщениями")

	// Даём время нодам запустить keygen и сгенерировать начальные сообщения
	time.Sleep(1 * time.Second)

	// Выполняем раунды keygen с обменом сообщениями
	maxIterations := 100
	noMessageIterations := 0

	// Очередь сообщений для рассылки
	pendingMessages := make([]*pb.KeygenMessage, 0)

	for iteration := 0; iteration < maxIterations; iteration++ {
		allCompleted := true
		totalMessages := 0

		// Сначала собираем все сообщения со всех нод через GetKeygenResult
		for _, client := range clients {
			result, err := client.GetKeygenResult(ctx, sessionID)
			fmt.Println("result", result, client.GetNodeID())
			if err != nil {
				return nil, fmt.Errorf("ошибка получения результата keygen от %s: %w", client.GetPartyID(), err)
			}

			if !result.Completed {
				allCompleted = false
			}

			pendingMessages = append(pendingMessages, result.OutgoingMessages...)
		}

		// Проверяем завершение до отправки сообщений
		if allCompleted {
			log.Printf("Keygen завершён на итерации %d", iteration)
			break
		}

		// Отправляем все накопленные сообщения и собираем ответы
		messagesToSend := pendingMessages
		pendingMessages = make([]*pb.KeygenMessage, 0)

		for _, msg := range messagesToSend {
			totalMessages++
			// Отправляем сообщение и собираем ответные сообщения
			responseMessages, err := r.broadcastAndCollect(ctx, msg)
			if err != nil {
				return nil, fmt.Errorf("ошибка рассылки сообщения: %w", err)
			}
			pendingMessages = append(pendingMessages, responseMessages...)
		}

		log.Printf("Итерация %d: отправлено=%d, получено=%d, allCompleted=%v",
			iteration, totalMessages, len(pendingMessages), allCompleted)

		if totalMessages == 0 && len(pendingMessages) == 0 {
			noMessageIterations++
			// Если 30 итераций подряд без сообщений - что-то пошло не так
			if noMessageIterations > 30 {
				log.Printf("Предупреждение: слишком много итераций без сообщений")
				break
			}
			// Небольшая пауза если нет сообщений
			time.Sleep(100 * time.Millisecond)
		} else {
			noMessageIterations = 0
		}

		// Пауза между итерациями для обработки сообщений
		time.Sleep(100 * time.Millisecond)
	}

	// Получаем финальный результат от первой ноды
	finalResult, err := clients[0].GetKeygenResult(ctx, sessionID)
	if err != nil {
		return nil, fmt.Errorf("не удалось получить финальный результат keygen: %w", err)
	}

	if !finalResult.Completed || !finalResult.Success {
		errMsg := "неизвестная ошибка"
		if finalResult.ErrorMessage != "" {
			errMsg = finalResult.ErrorMessage
		}
		return nil, fmt.Errorf("keygen не завершён успешно: %s", errMsg)
	}

	log.Printf("Keygen успешно завершён: publicKey=%s, address=%s",
		finalResult.Result.PublicKey, finalResult.Result.Address)

	return &model.KeygenResult{
		SessionID:    sessionID,
		PublicKey:    finalResult.Result.PublicKey,
		Address:      finalResult.Result.Address,
		Threshold:    finalResult.Result.Threshold,
		TotalParties: finalResult.Result.TotalParties,
	}, nil
}

// Nodes - резолвер для получения списка всех нод.
// Проверяет статус каждой ноды через HealthCheck.
func (r *queryResolver) Nodes(ctx context.Context) ([]*model.Node, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	nodes := make([]*model.Node, 0, len(r.nodes))
	for _, node := range r.nodes {
		// Проверяем статус ноды через HealthCheck
		if client, exists := r.NodeManager.GetNode(node.PartyID); exists {
			healthy, err := client.HealthCheck(ctx)
			if err != nil || !healthy {
				node.Status = model.NodeStatusOffline
			} else {
				node.Status = model.NodeStatusOnline
				node.LastSeen = time.Now().UTC().Format(time.RFC3339)
			}
		} else {
			node.Status = model.NodeStatusOffline
		}

		nodes = append(nodes, node)
	}
	return nodes, nil
}

// Node - резолвер для получения ноды по ID.
func (r *queryResolver) Node(ctx context.Context, id string) (*model.Node, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	node := r.nodes[id]
	// Проверяем статус ноды через HealthCheck
	if client, exists := r.NodeManager.GetNode(node.PartyID); exists {
		healthy, err := client.HealthCheck(ctx)
		if err != nil || !healthy {
			node.Status = model.NodeStatusOffline
		} else {
			node.Status = model.NodeStatusOnline
			node.LastSeen = time.Now().UTC().Format(time.RFC3339)
		}
	} else {
		node.Status = model.NodeStatusOffline
	}
	return node, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
