package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"fmt"
	"log"
	"time"

	pb "github.com/mpc_hsm/node/proto"
	"github.com/mpc_hsm/orchestrator/graph/model"
)

// RegisterNode - резолвер для регистрации новой ноды.
// Подключается к ноде по gRPC и получает её информацию.
func (r *mutationResolver) RegisterNode(ctx context.Context, input model.RegisterNodeInput) (*model.Node, error) {
	// Подключаемся к ноде через gRPC
	client, err := r.NodeManager.AddNode(ctx, input.Address)
	if err != nil {
		return nil, fmt.Errorf("не удалось подключиться к ноде %s: %w", input.Address, err)
	}

	// Получаем информацию о ноде
	info, err := client.GetNodeInfo(ctx)
	if err != nil {
		return nil, fmt.Errorf("не удалось получить информацию о ноде: %w", err)
	}

	r.mu.Lock()
	defer r.mu.Unlock()

	r.nodeCounter++
	id := fmt.Sprintf("node_%d", r.nodeCounter)

	// Используем данные от ноды, если не переданы явно
	partyID := input.PartyID
	if partyID == "" {
		partyID = info.PartyId
	}

	publicKey := input.PublicKey
	if publicKey == "" {
		publicKey = info.PublicKey
	}

	node := &model.Node{
		ID:        id,
		PartyID:   partyID,
		Address:   input.Address,
		PublicKey: publicKey,
		Status:    model.NodeStatusOnline,
		LastSeen:  time.Now().UTC().Format(time.RFC3339),
	}

	r.nodes[id] = node

	log.Printf("Нода зарегистрирована: %s (party: %s, address: %s)", id, partyID, input.Address)

	// Уведомляем подписчиков
	select {
	case r.nodeUpdates <- node:
	default:
	}

	return node, nil
}

// UnregisterNode - резолвер для удаления ноды из реестра.
func (r *mutationResolver) UnregisterNode(ctx context.Context, id string) (bool, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	if _, exists := r.nodes[id]; !exists {
		return false, fmt.Errorf("нода %s не найдена", id)
	}

	delete(r.nodes, id)
	return true, nil
}

// UpdateNodeStatus - резолвер для обновления статуса ноды.
func (r *mutationResolver) UpdateNodeStatus(ctx context.Context, id string, status model.NodeStatus) (*model.Node, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	node, exists := r.nodes[id]
	if !exists {
		return nil, fmt.Errorf("нода %s не найдена", id)
	}

	node.Status = status
	node.LastSeen = time.Now().UTC().Format(time.RFC3339)

	// Уведомляем подписчиков
	select {
	case r.nodeUpdates <- node:
	default:
	}

	return node, nil
}

// CreateSession - резолвер для создания новой MPC сессии.
func (r *mutationResolver) CreateSession(ctx context.Context, input model.CreateSessionInput) (*model.Session, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	r.sessionCounter++
	id := fmt.Sprintf("session_%d", r.sessionCounter)

	session := &model.Session{
		ID:           id,
		Type:         input.Type,
		Status:       model.SessionStatusPending,
		Participants: input.Participants,
		Threshold:    input.Threshold,
		CreatedAt:    time.Now().UTC().Format(time.RFC3339),
	}

	r.sessions[id] = session
	r.messages[id] = make([]*model.MPCMessage, 0)

	// Создаём канал для обновлений сессии
	r.sessionUpdates[id] = make(chan *model.Session, 100)

	return session, nil
}

// JoinSession - резолвер для присоединения участника к сессии.
func (r *mutationResolver) JoinSession(ctx context.Context, sessionID string, partyID string) (*model.Session, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	session, exists := r.sessions[sessionID]
	if !exists {
		return nil, fmt.Errorf("сессия %s не найдена", sessionID)
	}

	// Проверяем, не присоединился ли участник ранее
	for _, p := range session.Participants {
		if p == partyID {
			return session, nil // Уже присоединён
		}
	}

	session.Participants = append(session.Participants, partyID)

	// Уведомляем подписчиков
	if ch, ok := r.sessionUpdates[sessionID]; ok {
		select {
		case ch <- session:
		default:
		}
	}

	return session, nil
}

// CancelSession - резолвер для отмены сессии.
func (r *mutationResolver) CancelSession(ctx context.Context, id string) (bool, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	session, exists := r.sessions[id]
	if !exists {
		return false, fmt.Errorf("сессия %s не найдена", id)
	}

	session.Status = model.SessionStatusFailed
	now := time.Now().UTC().Format(time.RFC3339)
	session.CompletedAt = &now

	// Уведомляем подписчиков
	if ch, ok := r.sessionUpdates[id]; ok {
		select {
		case ch <- session:
		default:
		}
	}

	return true, nil
}

// StartKeygen - резолвер для запуска распределённой генерации ключей.
// Инициализирует keygen на всех подключённых нодах.
func (r *mutationResolver) StartKeygen(ctx context.Context, sessionID string) (*model.Session, error) {
	r.mu.Lock()
	session, exists := r.sessions[sessionID]
	if !exists {
		r.mu.Unlock()
		return nil, fmt.Errorf("сессия %s не найдена", sessionID)
	}

	if session.Type != model.SessionTypeKeygen {
		r.mu.Unlock()
		return nil, fmt.Errorf("сессия %s не является сессией генерации ключей", sessionID)
	}

	participants := session.Participants
	threshold := session.Threshold
	r.mu.Unlock()

	// Получаем клиенты нод для всех участников
	nodes, err := r.NodeManager.GetNodesByPartyIDs(participants)
	if err != nil {
		return nil, fmt.Errorf("не все ноды подключены: %w", err)
	}

	// Формируем информацию об участниках для протокола
	parties := make([]*pb.PartyInfo, len(participants))
	for i, partyID := range participants {
		node, _ := r.NodeManager.GetNode(partyID)
		parties[i] = &pb.PartyInfo{
			PartyId:    partyID,
			PartyIndex: int32(i),
			Address:    node.GetAddress(),
		}
	}

	// Инициализируем keygen на всех нодах
	for _, node := range nodes {
		if err := node.InitKeygen(ctx, sessionID, parties, threshold, "secp256k1"); err != nil {
			return nil, fmt.Errorf("не удалось инициализировать keygen на ноде %s: %w", node.GetPartyID(), err)
		}
		log.Printf("Keygen инициализирован на ноде %s", node.GetPartyID())
	}

	r.mu.Lock()
	session.Status = model.SessionStatusInProgress
	r.mu.Unlock()

	// Запускаем координацию сообщений в фоне с отдельным контекстом
	// (контекст HTTP-запроса завершится после возврата ответа)
	go r.coordinateKeygen(context.Background(), sessionID, nodes)

	// Уведомляем подписчиков
	if ch, ok := r.sessionUpdates[sessionID]; ok {
		select {
		case ch <- session:
		default:
		}
	}

	return session, nil
}

// StartSigning - резолвер для запуска распределённого подписания.
func (r *mutationResolver) StartSigning(ctx context.Context, input model.SigningInput) (*model.Session, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	r.sessionCounter++
	id := fmt.Sprintf("session_%d", r.sessionCounter)

	session := &model.Session{
		ID:           id,
		Type:         model.SessionTypeSigning,
		Status:       model.SessionStatusInProgress,
		Participants: input.Participants,
		Threshold:    int32(len(input.Participants)),
		CreatedAt:    time.Now().UTC().Format(time.RFC3339),
	}

	r.sessions[id] = session
	r.messages[id] = make([]*model.MPCMessage, 0)
	r.sessionUpdates[id] = make(chan *model.Session, 100)

	return session, nil
}

// SendMessage - резолвер для отправки MPC сообщения между участниками.
func (r *mutationResolver) SendMessage(ctx context.Context, input model.SendMessageInput) (*model.MPCMessage, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	session, exists := r.sessions[input.SessionID]
	if !exists {
		return nil, fmt.Errorf("сессия %s не найдена", input.SessionID)
	}

	r.messageCounter++
	id := fmt.Sprintf("msg_%d", r.messageCounter)

	isBroadcast := len(input.ToParties) == 0

	msg := &model.MPCMessage{
		ID:          id,
		SessionID:   input.SessionID,
		FromParty:   "", // Должно быть установлено из контекста/аутентификации
		ToParties:   input.ToParties,
		IsBroadcast: isBroadcast,
		Round:       int32(len(r.messages[input.SessionID]) + 1),
		Payload:     input.Payload,
		Timestamp:   time.Now().UTC().Format(time.RFC3339),
	}

	r.messages[input.SessionID] = append(r.messages[input.SessionID], msg)

	// Уведомляем подписчиков сообщений
	if isBroadcast {
		// Отправляем всем участникам
		for _, partyID := range session.Participants {
			key := fmt.Sprintf("%s:%s", partyID, input.SessionID)
			if ch, ok := r.messageStreams[key]; ok {
				select {
				case ch <- msg:
				default:
				}
			}
		}
	} else {
		// Отправляем конкретным участникам
		for _, partyID := range input.ToParties {
			key := fmt.Sprintf("%s:%s", partyID, input.SessionID)
			if ch, ok := r.messageStreams[key]; ok {
				select {
				case ch <- msg:
				default:
				}
			}
		}
	}

	return msg, nil
}

// AcknowledgeMessage - резолвер для подтверждения получения сообщения.
func (r *mutationResolver) AcknowledgeMessage(ctx context.Context, messageID string, partyID string) (bool, error) {
	// В реальной реализации здесь должно быть отслеживание подтверждений
	return true, nil
}

// HealthCheck - резолвер для проверки состояния оркестратора.
func (r *queryResolver) HealthCheck(ctx context.Context) (*model.HealthCheck, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	// Подсчёт статистики нод
	var onlineCount, offlineCount int
	for _, node := range r.nodes {
		if node.Status == model.NodeStatusOnline {
			onlineCount++
		} else {
			offlineCount++
		}
	}

	// Подсчёт статистики сессий
	var activeCount, pendingCount, completedCount, failedCount int
	for _, session := range r.sessions {
		switch session.Status {
		case model.SessionStatusInProgress:
			activeCount++
		case model.SessionStatusPending:
			pendingCount++
		case model.SessionStatusCompleted:
			completedCount++
		case model.SessionStatusFailed:
			failedCount++
		}
	}

	uptime := int32(time.Since(r.startTime).Seconds())

	return &model.HealthCheck{
		Status:    "ok",
		Timestamp: time.Now().UTC().Format(time.RFC3339),
		Version:   Version,
		Uptime:    uptime,
		Nodes: &model.NodeHealth{
			Total:   int32(len(r.nodes)),
			Online:  int32(onlineCount),
			Offline: int32(offlineCount),
		},
		Sessions: &model.SessionHealth{
			Active:    int32(activeCount),
			Pending:   int32(pendingCount),
			Completed: int32(completedCount),
			Failed:    int32(failedCount),
		},
	}, nil
}

// Nodes - резолвер для получения списка всех нод.
func (r *queryResolver) Nodes(ctx context.Context) ([]*model.Node, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	nodes := make([]*model.Node, 0, len(r.nodes))
	for _, node := range r.nodes {
		nodes = append(nodes, node)
	}
	return nodes, nil
}

// Node - резолвер для получения ноды по ID.
func (r *queryResolver) Node(ctx context.Context, id string) (*model.Node, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	node, exists := r.nodes[id]
	if !exists {
		return nil, nil
	}
	return node, nil
}

// OnlineNodes - резолвер для получения списка онлайн нод.
func (r *queryResolver) OnlineNodes(ctx context.Context) ([]*model.Node, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	nodes := make([]*model.Node, 0)
	for _, node := range r.nodes {
		if node.Status == model.NodeStatusOnline {
			nodes = append(nodes, node)
		}
	}
	return nodes, nil
}

// Sessions - резолвер для получения списка всех сессий.
func (r *queryResolver) Sessions(ctx context.Context) ([]*model.Session, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	sessions := make([]*model.Session, 0, len(r.sessions))
	for _, session := range r.sessions {
		sessions = append(sessions, session)
	}
	return sessions, nil
}

// Session - резолвер для получения сессии по ID.
func (r *queryResolver) Session(ctx context.Context, id string) (*model.Session, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	session, exists := r.sessions[id]
	if !exists {
		return nil, nil
	}
	return session, nil
}

// ActiveSessions - резолвер для получения списка активных сессий.
func (r *queryResolver) ActiveSessions(ctx context.Context) ([]*model.Session, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	sessions := make([]*model.Session, 0)
	for _, session := range r.sessions {
		if session.Status == model.SessionStatusPending || session.Status == model.SessionStatusInProgress {
			sessions = append(sessions, session)
		}
	}
	return sessions, nil
}

// PendingMessages - резолвер для получения ожидающих сообщений для участника.
func (r *queryResolver) PendingMessages(ctx context.Context, partyID string) ([]*model.MPCMessage, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	messages := make([]*model.MPCMessage, 0)
	for _, sessionMsgs := range r.messages {
		for _, msg := range sessionMsgs {
			if msg.IsBroadcast {
				messages = append(messages, msg)
			} else {
				for _, to := range msg.ToParties {
					if to == partyID {
						messages = append(messages, msg)
						break
					}
				}
			}
		}
	}
	return messages, nil
}

// NodeStatusChanged - подписка на изменения статуса нод.
func (r *subscriptionResolver) NodeStatusChanged(ctx context.Context) (<-chan *model.Node, error) {
	// Создаём новый канал для подписчика
	ch := make(chan *model.Node, 10)

	go func() {
		defer close(ch)
		for {
			select {
			case <-ctx.Done():
				return
			case node := <-r.nodeUpdates:
				select {
				case ch <- node:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return ch, nil
}

// SessionUpdated - подписка на обновления сессии.
func (r *subscriptionResolver) SessionUpdated(ctx context.Context, sessionID string) (<-chan *model.Session, error) {
	r.mu.Lock()
	if _, exists := r.sessionUpdates[sessionID]; !exists {
		r.sessionUpdates[sessionID] = make(chan *model.Session, 100)
	}
	sourceCh := r.sessionUpdates[sessionID]
	r.mu.Unlock()

	ch := make(chan *model.Session, 10)

	go func() {
		defer close(ch)
		for {
			select {
			case <-ctx.Done():
				return
			case session := <-sourceCh:
				select {
				case ch <- session:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return ch, nil
}

// Messages - подписка на поток MPC сообщений для участника.
func (r *subscriptionResolver) Messages(ctx context.Context, partyID string, sessionID string) (<-chan *model.MPCMessage, error) {
	key := fmt.Sprintf("%s:%s", partyID, sessionID)

	r.mu.Lock()
	if _, exists := r.messageStreams[key]; !exists {
		r.messageStreams[key] = make(chan *model.MPCMessage, 100)
	}
	sourceCh := r.messageStreams[key]
	r.mu.Unlock()

	ch := make(chan *model.MPCMessage, 10)

	go func() {
		defer close(ch)
		for {
			select {
			case <-ctx.Done():
				return
			case msg := <-sourceCh:
				select {
				case ch <- msg:
				case <-ctx.Done():
					return
				}
			}
		}
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
