package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.83

import (
	"context"
	"encoding/hex"
	"fmt"
	"time"

	pb "github.com/mpc_hsm/node/proto"
	"github.com/mpc_hsm/orchestrator/graph/model"
	"github.com/mpc_hsm/orchestrator/logger"
)

// RegisterNode - резолвер для регистрации новой ноды.
// Подключается к ноде по gRPC и получает её информацию.
// При подключении автоматически регистрируется Ed25519 публичный ключ ноды для верификации подписей.
func (r *mutationResolver) RegisterNode(ctx context.Context, input model.RegisterNodeInput) (*model.Node, error) {
	// Подключаемся к ноде через gRPC
	// NodeManager автоматически регистрирует публичный ключ ноды в PartyRegistry
	client, err := r.NodeManager.AddNode(ctx, input.Address)
	if err != nil {
		return nil, fmt.Errorf("не удалось подключиться к ноде %s: %w", input.Address, err)
	}

	// Получаем информацию о ноде
	info, err := client.GetNodeInfo(ctx)
	if err != nil {
		return nil, fmt.Errorf("не удалось получить информацию о ноде: %w", err)
	}

	r.mu.Lock()
	defer r.mu.Unlock()

	r.nodeCounter++
	id := fmt.Sprintf("node_%d", r.nodeCounter)

	// Используем данные от ноды, если не переданы явно
	var partyID string
	if input.PartyID != nil && *input.PartyID != "" {
		partyID = *input.PartyID
	} else {
		partyID = info.PartyId
	}

	var publicKey string
	if input.PublicKey != nil && *input.PublicKey != "" {
		publicKey = *input.PublicKey
	} else {
		publicKey = info.PublicKey
	}

	// Получаем signing public key для отображения
	signingPubKey := client.GetSigningPublicKeyBase64()

	node := &model.Node{
		ID:        id,
		PartyID:   partyID,
		Address:   input.Address,
		PublicKey: publicKey,
		Status:    model.NodeStatusOnline,
		LastSeen:  time.Now().UTC().Format(time.RFC3339),
	}

	r.nodes[id] = node

	// Логируем с информацией о security
	if signingPubKey != "" {
		logger.Info("Нода зарегистрирована", map[string]interface{}{
			"node_id":            id,
			"party_id":           partyID,
			"address":            input.Address,
			"signing_key_prefix": signingPubKey[:16],
		})
	} else {
		logger.Warn("Нода зарегистрирована без signing key", map[string]interface{}{
			"node_id":  id,
			"party_id": partyID,
			"address":  input.Address,
		})
	}

	return node, nil
}

// DeleteNode is the resolver for the deleteNode field.
func (r *mutationResolver) DeleteNode(ctx context.Context, id string) (*model.Node, error) {
	r.mu.Lock()
	defer r.mu.Unlock()

	// Проверяем, существует ли нода в локальном хранилище
	node, exists := r.nodes[id]
	if !exists {
		return nil, fmt.Errorf("нода %s не найдена", id)
	}

	// Удаляем из NodeManager по partyID
	if err := r.NodeManager.RemoveNode(node.PartyID); err != nil {
		logger.Warn("Не удалось удалить ноду из NodeManager", map[string]interface{}{
			"node_id":  id,
			"party_id": node.PartyID,
			"error":    err.Error(),
		})
	} else {
		logger.Info("Нода удалена", map[string]interface{}{
			"node_id":  id,
			"party_id": node.PartyID,
		})
	}

	// Удаляем из локального хранилища
	delete(r.nodes, id)

	node.Status = model.NodeStatusOffline
	return node, nil
}

// StartKeygen - резолвер для запуска распределённой генерации ключей (DKG).
// Координирует keygen между всеми участвующими MPC нодами.
func (r *mutationResolver) StartKeygen(ctx context.Context, input model.StartKeygenInput) (*model.KeygenResult, error) {
	// Определяем участников
	var participants []string
	if len(input.Participants) > 0 {
		participants = input.Participants
	} else {
		// Используем все зарегистрированные ноды
		r.mu.RLock()
		for _, node := range r.nodes {
			participants = append(participants, node.PartyID)
		}
		r.mu.RUnlock()
	}

	if len(participants) < 2 {
		return nil, fmt.Errorf("требуется минимум 2 участника для keygen, получено: %d", len(participants))
	}

	if int(input.Threshold) > len(participants) {
		return nil, fmt.Errorf("threshold (%d) не может быть больше количества участников (%d)", input.Threshold, len(participants))
	}

	if input.Threshold < 1 {
		return nil, fmt.Errorf("threshold должен быть >= 1")
	}

	// Определяем кривую
	curve := "secp256k1"
	if input.Curve != nil && *input.Curve != "" {
		curve = *input.Curve
	}

	// SECURITY: Генерируем криптографически случайный ID сессии
	sessionID := generateSecureSessionID("keygen")

	logger.Info("Запуск keygen сессии", map[string]interface{}{
		"session_id":   sessionID,
		"participants": participants,
		"threshold":    input.Threshold,
		"curve":        curve,
	})

	// Получаем клиентов для всех участников
	clients, err := r.NodeManager.GetNodesByPartyIDs(participants)
	if err != nil {
		return nil, fmt.Errorf("не удалось получить ноды: %w", err)
	}

	// Формируем информацию о участниках с signing public keys
	parties := make([]*pb.PartyInfo, len(participants))
	for i, partyID := range participants {
		client, _ := r.NodeManager.GetNode(partyID)
		parties[i] = &pb.PartyInfo{
			PartyId:          partyID,
			PartyIndex:       int32(i),
			Address:          client.GetAddress(),
			SigningPublicKey: client.GetSigningPublicKeyBase64(), // Ed25519 ключ для верификации
		}
	}

	// Инициализируем keygen на всех нодах
	for _, client := range clients {
		if err := client.InitKeygen(ctx, sessionID, parties, input.Threshold, curve); err != nil {
			return nil, fmt.Errorf("не удалось инициализировать keygen на ноде %s: %w", client.GetPartyID(), err)
		}
	}

	logger.Info("Keygen инициализирован, начинаем обмен сообщениями", map[string]interface{}{
		"session_id": sessionID,
	})

	// Даём время нодам запустить keygen и сгенерировать начальные сообщения
	initSleep := time.Duration(r.config.Session.InitializationSleepMs) * time.Millisecond
	time.Sleep(initSleep)

	// Выполняем раунды keygen с обменом сообщениями
	maxIterations := r.config.Session.MaxIterations
	noMessageIterations := 0
	iterationSleep := time.Duration(r.config.Session.IterationSleepMs) * time.Millisecond
	noMessageTimeout := r.config.Session.NoMessageTimeout

	// Очередь сообщений для рассылки
	pendingMessages := make([]*pb.KeygenMessage, 0)

	for iteration := 0; iteration < maxIterations; iteration++ {
		allCompleted := true
		totalMessages := 0

		// Сначала собираем все сообщения со всех нод через GetKeygenResult
		for _, client := range clients {
			result, err := client.GetKeygenResult(ctx, sessionID)
			if err != nil {
				logger.Error("Ошибка получения результата keygen", map[string]interface{}{
					"session_id": sessionID,
					"party_id":   client.GetPartyID(),
					"error":      err.Error(),
				})
				return nil, fmt.Errorf("ошибка получения результата keygen от %s: %w", client.GetPartyID(), err)
			}

			if !result.Completed {
				allCompleted = false
			}

			pendingMessages = append(pendingMessages, result.OutgoingMessages...)
		}

		// Проверяем завершение до отправки сообщений
		if allCompleted {
			logger.Info("Keygen завершён", map[string]interface{}{
				"session_id": sessionID,
				"iteration":  iteration,
			})
			break
		}

		// Отправляем все накопленные сообщения и собираем ответы
		messagesToSend := pendingMessages
		pendingMessages = make([]*pb.KeygenMessage, 0)

		for _, msg := range messagesToSend {
			totalMessages++
			// Отправляем сообщение и собираем ответные сообщения
			responseMessages, err := r.broadcastAndCollect(ctx, msg)
			if err != nil {
				return nil, fmt.Errorf("ошибка рассылки сообщения: %w", err)
			}
			pendingMessages = append(pendingMessages, responseMessages...)
		}

		logger.Debug("Keygen итерация", map[string]interface{}{
			"session_id":     sessionID,
			"iteration":      iteration,
			"sent_messages":  totalMessages,
			"recv_messages":  len(pendingMessages),
			"all_completed":  allCompleted,
		})

		if totalMessages == 0 && len(pendingMessages) == 0 {
			noMessageIterations++
			// Если слишком много итераций подряд без сообщений - что-то пошло не так
			if noMessageIterations > noMessageTimeout {
				logger.Warn("Слишком много итераций без сообщений", map[string]interface{}{
					"session_id":           sessionID,
					"no_message_iterations": noMessageIterations,
				})
				break
			}
			// Небольшая пауза если нет сообщений
			time.Sleep(iterationSleep)
		} else {
			noMessageIterations = 0
		}

		// Пауза между итерациями для обработки сообщений
		time.Sleep(iterationSleep)
	}

	// Получаем финальный результат от первой ноды
	finalResult, err := clients[0].GetKeygenResult(ctx, sessionID)
	if err != nil {
		return nil, fmt.Errorf("не удалось получить финальный результат keygen: %w", err)
	}

	if !finalResult.Completed || !finalResult.Success {
		errMsg := "неизвестная ошибка"
		if finalResult.ErrorMessage != "" {
			errMsg = finalResult.ErrorMessage
		}
		return nil, fmt.Errorf("keygen не завершён успешно: %s", errMsg)
	}

	logger.Info("Keygen успешно завершён", map[string]interface{}{
		"session_id": sessionID,
		"public_key": finalResult.Result.PublicKey,
		"address":    finalResult.Result.Address,
		"threshold":  finalResult.Result.Threshold,
	})

	return &model.KeygenResult{
		SessionID:    sessionID,
		PublicKey:    finalResult.Result.PublicKey,
		Address:      finalResult.Result.Address,
		Threshold:    finalResult.Result.Threshold,
		TotalParties: finalResult.Result.TotalParties,
	}, nil
}

// StartSigning - резолвер для запуска распределённого подписания (TSS).
// Координирует signing между участвующими MPC нодами.
func (r *mutationResolver) StartSigning(ctx context.Context, input model.StartSigningInput) (*model.SigningResult, error) {
	// Определяем участников
	var participants []string
	if len(input.Participants) > 0 {
		participants = input.Participants
	} else {
		// Используем все зарегистрированные ноды
		r.mu.RLock()
		for _, node := range r.nodes {
			participants = append(participants, node.PartyID)
		}
		r.mu.RUnlock()
	}

	if len(participants) < 2 {
		return nil, fmt.Errorf("требуется минимум 2 участника для signing, получено: %d", len(participants))
	}

	// Конвертируем сообщение в байты
	var messageBytes []byte
	if len(input.Message) > 2 && input.Message[:2] == "0x" {
		// Hex-encoded message
		var err error
		messageBytes, err = hex.DecodeString(input.Message[2:])
		if err != nil {
			return nil, fmt.Errorf("неверный hex формат сообщения: %w", err)
		}
	} else {
		// UTF-8 строка
		messageBytes = []byte(input.Message)
	}

	// SECURITY: Генерируем криптографически случайный ID сессии
	sessionID := generateSecureSessionID("signing")

	logger.Info("Запуск signing сессии", map[string]interface{}{
		"session_id":   sessionID,
		"address":      input.Address,
		"participants": participants,
		"message_len":  len(messageBytes),
	})

	// Получаем клиентов для всех участников
	clients, err := r.NodeManager.GetNodesByPartyIDs(participants)
	if err != nil {
		return nil, fmt.Errorf("не удалось получить ноды: %w", err)
	}

	// Формируем информацию о участниках
	parties := make([]*pb.PartyInfo, len(participants))
	for i, partyID := range participants {
		client, _ := r.NodeManager.GetNode(partyID)
		parties[i] = &pb.PartyInfo{
			PartyId:          partyID,
			PartyIndex:       int32(i),
			Address:          client.GetAddress(),
			SigningPublicKey: client.GetSigningPublicKeyBase64(),
		}
	}

	// Инициализируем signing на всех нодах
	for _, client := range clients {
		if err := client.InitSigning(ctx, sessionID, input.Address, messageBytes, parties); err != nil {
			return nil, fmt.Errorf("не удалось инициализировать signing на ноде %s: %w", client.GetPartyID(), err)
		}
	}

	logger.Info("Signing инициализирован, начинаем обмен сообщениями", map[string]interface{}{
		"session_id": sessionID,
	})

	// Даём время нодам запустить signing и сгенерировать начальные сообщения
	initSleep := time.Duration(r.config.Session.InitializationSleepMs) * time.Millisecond
	time.Sleep(initSleep)

	// Выполняем раунды signing с обменом сообщениями
	maxIterations := r.config.Session.MaxIterations
	noMessageIterations := 0
	iterationSleep := time.Duration(r.config.Session.IterationSleepMs) * time.Millisecond
	noMessageTimeout := r.config.Session.NoMessageTimeout

	// Очередь сообщений для рассылки
	pendingMessages := make([]*pb.SigningMessage, 0)

	for iteration := 0; iteration < maxIterations; iteration++ {
		allCompleted := true
		totalMessages := 0

		// Собираем сообщения со всех нод через GetSigningResult
		for _, client := range clients {
			result, err := client.GetSigningResult(ctx, sessionID)
			if err != nil {
				logger.Error("Ошибка получения результата signing", map[string]interface{}{
					"session_id": sessionID,
					"party_id":   client.GetPartyID(),
					"error":      err.Error(),
				})
				return nil, fmt.Errorf("ошибка получения результата signing от %s: %w", client.GetPartyID(), err)
			}

			if !result.Completed {
				allCompleted = false
			}

			pendingMessages = append(pendingMessages, result.OutgoingMessages...)
		}

		// Проверяем завершение
		if allCompleted {
			logger.Info("Signing завершён", map[string]interface{}{
				"session_id": sessionID,
				"iteration":  iteration,
			})
			break
		}

		// Отправляем все накопленные сообщения
		messagesToSend := pendingMessages
		pendingMessages = make([]*pb.SigningMessage, 0)

		for _, msg := range messagesToSend {
			totalMessages++
			// Отправляем сообщение и собираем ответные
			responseMessages, err := r.broadcastSigningAndCollect(ctx, msg)
			if err != nil {
				return nil, fmt.Errorf("ошибка рассылки signing сообщения: %w", err)
			}
			pendingMessages = append(pendingMessages, responseMessages...)
		}

		logger.Debug("Signing итерация", map[string]interface{}{
			"session_id":    sessionID,
			"iteration":     iteration,
			"sent_messages": totalMessages,
			"recv_messages": len(pendingMessages),
			"all_completed": allCompleted,
		})

		if totalMessages == 0 && len(pendingMessages) == 0 {
			noMessageIterations++
			if noMessageIterations > noMessageTimeout {
				logger.Warn("Слишком много итераций без сообщений", map[string]interface{}{
					"session_id":            sessionID,
					"no_message_iterations": noMessageIterations,
				})
				break
			}
			time.Sleep(iterationSleep)
		} else {
			noMessageIterations = 0
		}

		time.Sleep(iterationSleep)
	}

	// Получаем финальный результат от первой ноды
	finalResult, err := clients[0].GetSigningResult(ctx, sessionID)
	if err != nil {
		return nil, fmt.Errorf("не удалось получить финальный результат signing: %w", err)
	}

	if !finalResult.Completed || !finalResult.Success {
		errMsg := "неизвестная ошибка"
		if finalResult.ErrorMessage != "" {
			errMsg = finalResult.ErrorMessage
		}
		return nil, fmt.Errorf("signing не завершён успешно: %s", errMsg)
	}

	logger.Info("Signing успешно завершён", map[string]interface{}{
		"session_id": sessionID,
		"signature":  finalResult.Result.Signature,
		"address":    input.Address,
	})

	return &model.SigningResult{
		SessionID: sessionID,
		Signature: finalResult.Result.Signature,
		R:         finalResult.Result.R,
		S:         finalResult.Result.S,
		V:         finalResult.Result.V,
	}, nil
}

// Nodes - резолвер для получения списка всех нод.
// Проверяет статус каждой ноды через HealthCheck.
func (r *queryResolver) Nodes(ctx context.Context) ([]*model.Node, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	nodes := make([]*model.Node, 0, len(r.nodes))
	for _, node := range r.nodes {
		// Проверяем статус ноды через HealthCheck
		if client, exists := r.NodeManager.GetNode(node.PartyID); exists {
			healthy, err := client.HealthCheck(ctx)
			if err != nil || !healthy {
				node.Status = model.NodeStatusOffline
			} else {
				node.Status = model.NodeStatusOnline
				node.LastSeen = time.Now().UTC().Format(time.RFC3339)
			}
		} else {
			node.Status = model.NodeStatusOffline
		}

		nodes = append(nodes, node)
	}
	return nodes, nil
}

// Node - резолвер для получения ноды по ID.
func (r *queryResolver) Node(ctx context.Context, id string) (*model.Node, error) {
	r.mu.RLock()
	defer r.mu.RUnlock()

	node := r.nodes[id]
	// Проверяем статус ноды через HealthCheck
	if client, exists := r.NodeManager.GetNode(node.PartyID); exists {
		healthy, err := client.HealthCheck(ctx)
		if err != nil || !healthy {
			node.Status = model.NodeStatusOffline
		} else {
			node.Status = model.NodeStatusOnline
			node.LastSeen = time.Now().UTC().Format(time.RFC3339)
		}
	} else {
		node.Status = model.NodeStatusOffline
	}
	return node, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
