// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type KeygenInput struct {
	Threshold    int32 `json:"threshold"`
	TotalParties int32 `json:"totalParties"`
}

type KeygenResult struct {
	PublicKey   string        `json:"publicKey"`
	PrivateKey  string        `json:"privateKey"`
	Address     string        `json:"address"`
	PartyIds    []string      `json:"partyIds"`
	Shares      []*PartyShare `json:"shares"`
	Threshold   int32         `json:"threshold"`
	TotalShares int32         `json:"totalShares"`
	Success     bool          `json:"success"`
	Message     string        `json:"message"`
}

type Mutation struct {
}

type NewTodo struct {
	Text   string `json:"text"`
	UserID string `json:"userId"`
}

type PartyShare struct {
	PartyID    string `json:"partyId"`
	ShareID    string `json:"shareId"`
	ShareValue string `json:"shareValue"`
}

type Query struct {
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
	User *User  `json:"user"`
}

type User struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}
