// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type CreateSessionInput struct {
	Type         SessionType `json:"type"`
	Participants []string    `json:"participants"`
	Threshold    int32       `json:"threshold"`
}

type HealthCheck struct {
	Status    string         `json:"status"`
	Timestamp string         `json:"timestamp"`
	Version   string         `json:"version"`
	Uptime    int32          `json:"uptime"`
	Nodes     *NodeHealth    `json:"nodes"`
	Sessions  *SessionHealth `json:"sessions"`
}

type KeyShare struct {
	PartyID     string `json:"partyId"`
	PublicShare string `json:"publicShare"`
}

type KeygenResult struct {
	SessionID    string      `json:"sessionId"`
	PublicKey    string      `json:"publicKey"`
	Address      string      `json:"address"`
	Shares       []*KeyShare `json:"shares"`
	Threshold    int32       `json:"threshold"`
	TotalParties int32       `json:"totalParties"`
}

type MPCMessage struct {
	ID          string   `json:"id"`
	SessionID   string   `json:"sessionId"`
	FromParty   string   `json:"fromParty"`
	ToParties   []string `json:"toParties"`
	IsBroadcast bool     `json:"isBroadcast"`
	Round       int32    `json:"round"`
	Payload     string   `json:"payload"`
	Timestamp   string   `json:"timestamp"`
}

type Mutation struct {
}

type Node struct {
	ID        string     `json:"id"`
	PartyID   string     `json:"partyId"`
	Address   string     `json:"address"`
	PublicKey string     `json:"publicKey"`
	Status    NodeStatus `json:"status"`
	LastSeen  string     `json:"lastSeen"`
}

type NodeHealth struct {
	Total   int32 `json:"total"`
	Online  int32 `json:"online"`
	Offline int32 `json:"offline"`
}

type Query struct {
}

type RegisterNodeInput struct {
	PartyID   string `json:"partyId"`
	Address   string `json:"address"`
	PublicKey string `json:"publicKey"`
}

type SendMessageInput struct {
	SessionID string   `json:"sessionId"`
	ToParties []string `json:"toParties,omitempty"`
	Payload   string   `json:"payload"`
}

type Session struct {
	ID           string         `json:"id"`
	Type         SessionType    `json:"type"`
	Status       SessionStatus  `json:"status"`
	Participants []string       `json:"participants"`
	Threshold    int32          `json:"threshold"`
	CreatedAt    string         `json:"createdAt"`
	CompletedAt  *string        `json:"completedAt,omitempty"`
	Result       *SessionResult `json:"result,omitempty"`
}

type SessionHealth struct {
	Active    int32 `json:"active"`
	Pending   int32 `json:"pending"`
	Completed int32 `json:"completed"`
	Failed    int32 `json:"failed"`
}

type SessionResult struct {
	Success bool    `json:"success"`
	Message string  `json:"message"`
	Data    *string `json:"data,omitempty"`
}

type SigningInput struct {
	KeyID        string   `json:"keyId"`
	Message      string   `json:"message"`
	Participants []string `json:"participants"`
}

type SigningResult struct {
	SessionID string `json:"sessionId"`
	Signature string `json:"signature"`
	R         string `json:"r"`
	S         string `json:"s"`
	V         int32  `json:"v"`
}

type Subscription struct {
}

type NodeStatus string

const (
	NodeStatusOnline  NodeStatus = "ONLINE"
	NodeStatusOffline NodeStatus = "OFFLINE"
	NodeStatusBusy    NodeStatus = "BUSY"
	NodeStatusError   NodeStatus = "ERROR"
)

var AllNodeStatus = []NodeStatus{
	NodeStatusOnline,
	NodeStatusOffline,
	NodeStatusBusy,
	NodeStatusError,
}

func (e NodeStatus) IsValid() bool {
	switch e {
	case NodeStatusOnline, NodeStatusOffline, NodeStatusBusy, NodeStatusError:
		return true
	}
	return false
}

func (e NodeStatus) String() string {
	return string(e)
}

func (e *NodeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeStatus", str)
	}
	return nil
}

func (e NodeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionStatus string

const (
	SessionStatusPending    SessionStatus = "PENDING"
	SessionStatusInProgress SessionStatus = "IN_PROGRESS"
	SessionStatusCompleted  SessionStatus = "COMPLETED"
	SessionStatusFailed     SessionStatus = "FAILED"
)

var AllSessionStatus = []SessionStatus{
	SessionStatusPending,
	SessionStatusInProgress,
	SessionStatusCompleted,
	SessionStatusFailed,
}

func (e SessionStatus) IsValid() bool {
	switch e {
	case SessionStatusPending, SessionStatusInProgress, SessionStatusCompleted, SessionStatusFailed:
		return true
	}
	return false
}

func (e SessionStatus) String() string {
	return string(e)
}

func (e *SessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionStatus", str)
	}
	return nil
}

func (e SessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionType string

const (
	SessionTypeKeygen    SessionType = "KEYGEN"
	SessionTypeSigning   SessionType = "SIGNING"
	SessionTypeResharing SessionType = "RESHARING"
)

var AllSessionType = []SessionType{
	SessionTypeKeygen,
	SessionTypeSigning,
	SessionTypeResharing,
}

func (e SessionType) IsValid() bool {
	switch e {
	case SessionTypeKeygen, SessionTypeSigning, SessionTypeResharing:
		return true
	}
	return false
}

func (e SessionType) String() string {
	return string(e)
}

func (e *SessionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionType", str)
	}
	return nil
}

func (e SessionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
