// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type KeygenResult struct {
	SessionID    string `json:"sessionId"`
	PublicKey    string `json:"publicKey"`
	Address      string `json:"address"`
	Threshold    int32  `json:"threshold"`
	TotalParties int32  `json:"totalParties"`
}

type Mutation struct {
}

type Node struct {
	ID               string     `json:"id"`
	PartyID          string     `json:"partyId"`
	Address          string     `json:"address"`
	Status           NodeStatus `json:"status"`
	LastSeen         string     `json:"lastSeen"`
	SigningPublicKey string     `json:"signingPublicKey"`
}

type Query struct {
}

type RegisterNodeInput struct {
	// Адрес ноды для подключения (обязательный)
	Address string `json:"address"`
	// Party ID ноды (опционально - получается от ноды автоматически)
	PartyID *string `json:"partyId,omitempty"`
}

type SigningResult struct {
	SessionID string `json:"sessionId"`
	Signature string `json:"signature"`
	R         string `json:"r"`
	S         string `json:"s"`
	V         int32  `json:"v"`
}

type StartKeygenInput struct {
	// Список party ID участников генерации ключей.
	// Если не указан - используются все зарегистрированные ноды.
	Participants []string `json:"participants,omitempty"`
	// Пороговое значение (минимальное количество участников для подписания).
	// Должно быть <= количества участников.
	Threshold int32 `json:"threshold"`
	// Эллиптическая кривая для ключа: secp256k1, ed25519 и др.
	// По умолчанию: secp256k1
	Curve *string `json:"curve,omitempty"`
}

type StartSigningInput struct {
	// Ethereum адрес кошелька для подписания (публичный ключ должен быть сгенерирован ранее)
	Address string `json:"address"`
	// Сообщение для подписания (hex или UTF-8 строка)
	Message string `json:"message"`
	// Список party ID участников подписания (опционально - используются все ноды с share для этого адреса)
	Participants []string `json:"participants,omitempty"`
}

type NodeStatus string

const (
	NodeStatusOnline  NodeStatus = "ONLINE"
	NodeStatusOffline NodeStatus = "OFFLINE"
	NodeStatusBusy    NodeStatus = "BUSY"
	NodeStatusError   NodeStatus = "ERROR"
)

var AllNodeStatus = []NodeStatus{
	NodeStatusOnline,
	NodeStatusOffline,
	NodeStatusBusy,
	NodeStatusError,
}

func (e NodeStatus) IsValid() bool {
	switch e {
	case NodeStatusOnline, NodeStatusOffline, NodeStatusBusy, NodeStatusError:
		return true
	}
	return false
}

func (e NodeStatus) String() string {
	return string(e)
}

func (e *NodeStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = NodeStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid NodeStatus", str)
	}
	return nil
}

func (e NodeStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *NodeStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e NodeStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionStatus string

const (
	SessionStatusPending    SessionStatus = "PENDING"
	SessionStatusInProgress SessionStatus = "IN_PROGRESS"
	SessionStatusCompleted  SessionStatus = "COMPLETED"
	SessionStatusFailed     SessionStatus = "FAILED"
)

var AllSessionStatus = []SessionStatus{
	SessionStatusPending,
	SessionStatusInProgress,
	SessionStatusCompleted,
	SessionStatusFailed,
}

func (e SessionStatus) IsValid() bool {
	switch e {
	case SessionStatusPending, SessionStatusInProgress, SessionStatusCompleted, SessionStatusFailed:
		return true
	}
	return false
}

func (e SessionStatus) String() string {
	return string(e)
}

func (e *SessionStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionStatus", str)
	}
	return nil
}

func (e SessionStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SessionType string

const (
	SessionTypeKeygen    SessionType = "KEYGEN"
	SessionTypeSigning   SessionType = "SIGNING"
	SessionTypeResharing SessionType = "RESHARING"
)

var AllSessionType = []SessionType{
	SessionTypeKeygen,
	SessionTypeSigning,
	SessionTypeResharing,
}

func (e SessionType) IsValid() bool {
	switch e {
	case SessionTypeKeygen, SessionTypeSigning, SessionTypeResharing:
		return true
	}
	return false
}

func (e SessionType) String() string {
	return string(e)
}

func (e *SessionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SessionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SessionType", str)
	}
	return nil
}

func (e SessionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SessionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SessionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
