// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_ONLINE      NodeStatus = 1
	NodeStatus_NODE_STATUS_OFFLINE     NodeStatus = 2
	NodeStatus_NODE_STATUS_BUSY        NodeStatus = 3
	NodeStatus_NODE_STATUS_ERROR       NodeStatus = 4
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ONLINE",
		2: "NODE_STATUS_OFFLINE",
		3: "NODE_STATUS_BUSY",
		4: "NODE_STATUS_ERROR",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ONLINE":      1,
		"NODE_STATUS_OFFLINE":     2,
		"NODE_STATUS_BUSY":        3,
		"NODE_STATUS_ERROR":       4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

type ControlType int32

const (
	ControlType_CONTROL_TYPE_UNSPECIFIED   ControlType = 0
	ControlType_CONTROL_TYPE_SESSION_START ControlType = 1
	ControlType_CONTROL_TYPE_SESSION_END   ControlType = 2
	ControlType_CONTROL_TYPE_ERROR         ControlType = 3
	ControlType_CONTROL_TYPE_HEARTBEAT     ControlType = 4
)

// Enum value maps for ControlType.
var (
	ControlType_name = map[int32]string{
		0: "CONTROL_TYPE_UNSPECIFIED",
		1: "CONTROL_TYPE_SESSION_START",
		2: "CONTROL_TYPE_SESSION_END",
		3: "CONTROL_TYPE_ERROR",
		4: "CONTROL_TYPE_HEARTBEAT",
	}
	ControlType_value = map[string]int32{
		"CONTROL_TYPE_UNSPECIFIED":   0,
		"CONTROL_TYPE_SESSION_START": 1,
		"CONTROL_TYPE_SESSION_END":   2,
		"CONTROL_TYPE_ERROR":         3,
		"CONTROL_TYPE_HEARTBEAT":     4,
	}
)

func (x ControlType) Enum() *ControlType {
	p := new(ControlType)
	*p = x
	return p
}

func (x ControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[1].Descriptor()
}

func (ControlType) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[1]
}

func (x ControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlType.Descriptor instead.
func (ControlType) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

type GetNodeInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NodeId          string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PartyId         string                 `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	PublicKey       string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address         string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Status          NodeStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=mpcnode.NodeStatus" json:"status,omitempty"`
	SupportedCurves []string               `protobuf:"bytes,6,rep,name=supported_curves,json=supportedCurves,proto3" json:"supported_curves,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{3}
}

func (x *GetNodeInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetNodeInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetNodeInfoResponse) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *GetNodeInfoResponse) GetSupportedCurves() []string {
	if x != nil {
		return x.SupportedCurves
	}
	return nil
}

type InitKeygenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Parties       []*PartyInfo           `protobuf:"bytes,2,rep,name=parties,proto3" json:"parties,omitempty"`
	Threshold     int32                  `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Curve         string                 `protobuf:"bytes,4,opt,name=curve,proto3" json:"curve,omitempty"` // secp256k1, ed25519, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitKeygenRequest) Reset() {
	*x = InitKeygenRequest{}
	mi := &file_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitKeygenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitKeygenRequest) ProtoMessage() {}

func (x *InitKeygenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitKeygenRequest.ProtoReflect.Descriptor instead.
func (*InitKeygenRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *InitKeygenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitKeygenRequest) GetParties() []*PartyInfo {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *InitKeygenRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *InitKeygenRequest) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

type PartyInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	PartyIndex    int32                  `protobuf:"varint,2,opt,name=party_index,json=partyIndex,proto3" json:"party_index,omitempty"`
	Address       string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PartyInfo) Reset() {
	*x = PartyInfo{}
	mi := &file_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInfo) ProtoMessage() {}

func (x *PartyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInfo.ProtoReflect.Descriptor instead.
func (*PartyInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *PartyInfo) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyInfo) GetPartyIndex() int32 {
	if x != nil {
		return x.PartyIndex
	}
	return 0
}

func (x *PartyInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type InitKeygenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitKeygenResponse) Reset() {
	*x = InitKeygenResponse{}
	mi := &file_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitKeygenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitKeygenResponse) ProtoMessage() {}

func (x *InitKeygenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitKeygenResponse.ProtoReflect.Descriptor instead.
func (*InitKeygenResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *InitKeygenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitKeygenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InitKeygenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type KeygenMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromParty     string                 `protobuf:"bytes,2,opt,name=from_party,json=fromParty,proto3" json:"from_party,omitempty"`
	ToParties     []string               `protobuf:"bytes,3,rep,name=to_parties,json=toParties,proto3" json:"to_parties,omitempty"` // пусто = broadcast
	Round         int32                  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	IsBroadcast   bool                   `protobuf:"varint,6,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenMessage) Reset() {
	*x = KeygenMessage{}
	mi := &file_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenMessage) ProtoMessage() {}

func (x *KeygenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenMessage.ProtoReflect.Descriptor instead.
func (*KeygenMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *KeygenMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KeygenMessage) GetFromParty() string {
	if x != nil {
		return x.FromParty
	}
	return ""
}

func (x *KeygenMessage) GetToParties() []string {
	if x != nil {
		return x.ToParties
	}
	return nil
}

func (x *KeygenMessage) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *KeygenMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *KeygenMessage) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

type KeygenMessageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutgoingMessages []*KeygenMessage       `protobuf:"bytes,3,rep,name=outgoing_messages,json=outgoingMessages,proto3" json:"outgoing_messages,omitempty"` // исходящие сообщения для других участников
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KeygenMessageResponse) Reset() {
	*x = KeygenMessageResponse{}
	mi := &file_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenMessageResponse) ProtoMessage() {}

func (x *KeygenMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenMessageResponse.ProtoReflect.Descriptor instead.
func (*KeygenMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *KeygenMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KeygenMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *KeygenMessageResponse) GetOutgoingMessages() []*KeygenMessage {
	if x != nil {
		return x.OutgoingMessages
	}
	return nil
}

type GetKeygenResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeygenResultRequest) Reset() {
	*x = GetKeygenResultRequest{}
	mi := &file_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeygenResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeygenResultRequest) ProtoMessage() {}

func (x *GetKeygenResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeygenResultRequest.ProtoReflect.Descriptor instead.
func (*GetKeygenResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{9}
}

func (x *GetKeygenResultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetKeygenResultResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Completed        bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Result           *KeygenResult          `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	OutgoingMessages []*KeygenMessage       `protobuf:"bytes,5,rep,name=outgoing_messages,json=outgoingMessages,proto3" json:"outgoing_messages,omitempty"` // исходящие сообщения для маршрутизации
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetKeygenResultResponse) Reset() {
	*x = GetKeygenResultResponse{}
	mi := &file_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeygenResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeygenResultResponse) ProtoMessage() {}

func (x *GetKeygenResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeygenResultResponse.ProtoReflect.Descriptor instead.
func (*GetKeygenResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *GetKeygenResultResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *GetKeygenResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetKeygenResultResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetKeygenResultResponse) GetResult() *KeygenResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetKeygenResultResponse) GetOutgoingMessages() []*KeygenMessage {
	if x != nil {
		return x.OutgoingMessages
	}
	return nil
}

type KeygenResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                            // Ethereum/Bitcoin адрес
	PublicShare   string                 `protobuf:"bytes,3,opt,name=public_share,json=publicShare,proto3" json:"public_share,omitempty"` // публичная часть доли ключа
	PartyIndex    int32                  `protobuf:"varint,4,opt,name=party_index,json=partyIndex,proto3" json:"party_index,omitempty"`
	Threshold     int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalParties  int32                  `protobuf:"varint,6,opt,name=total_parties,json=totalParties,proto3" json:"total_parties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenResult) Reset() {
	*x = KeygenResult{}
	mi := &file_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenResult) ProtoMessage() {}

func (x *KeygenResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenResult.ProtoReflect.Descriptor instead.
func (*KeygenResult) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *KeygenResult) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *KeygenResult) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *KeygenResult) GetPublicShare() string {
	if x != nil {
		return x.PublicShare
	}
	return ""
}

func (x *KeygenResult) GetPartyIndex() int32 {
	if x != nil {
		return x.PartyIndex
	}
	return 0
}

func (x *KeygenResult) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *KeygenResult) GetTotalParties() int32 {
	if x != nil {
		return x.TotalParties
	}
	return 0
}

type InitSigningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"` // ID ключа для подписания
	MessageToSign []byte                 `protobuf:"bytes,3,opt,name=message_to_sign,json=messageToSign,proto3" json:"message_to_sign,omitempty"`
	Parties       []*PartyInfo           `protobuf:"bytes,4,rep,name=parties,proto3" json:"parties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSigningRequest) Reset() {
	*x = InitSigningRequest{}
	mi := &file_proto_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSigningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSigningRequest) ProtoMessage() {}

func (x *InitSigningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSigningRequest.ProtoReflect.Descriptor instead.
func (*InitSigningRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{12}
}

func (x *InitSigningRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitSigningRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *InitSigningRequest) GetMessageToSign() []byte {
	if x != nil {
		return x.MessageToSign
	}
	return nil
}

func (x *InitSigningRequest) GetParties() []*PartyInfo {
	if x != nil {
		return x.Parties
	}
	return nil
}

type InitSigningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSigningResponse) Reset() {
	*x = InitSigningResponse{}
	mi := &file_proto_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSigningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSigningResponse) ProtoMessage() {}

func (x *InitSigningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSigningResponse.ProtoReflect.Descriptor instead.
func (*InitSigningResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{13}
}

func (x *InitSigningResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitSigningResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InitSigningResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SigningMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromParty     string                 `protobuf:"bytes,2,opt,name=from_party,json=fromParty,proto3" json:"from_party,omitempty"`
	ToParties     []string               `protobuf:"bytes,3,rep,name=to_parties,json=toParties,proto3" json:"to_parties,omitempty"`
	Round         int32                  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Payload       []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	IsBroadcast   bool                   `protobuf:"varint,6,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningMessage) Reset() {
	*x = SigningMessage{}
	mi := &file_proto_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningMessage) ProtoMessage() {}

func (x *SigningMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningMessage.ProtoReflect.Descriptor instead.
func (*SigningMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{14}
}

func (x *SigningMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SigningMessage) GetFromParty() string {
	if x != nil {
		return x.FromParty
	}
	return ""
}

func (x *SigningMessage) GetToParties() []string {
	if x != nil {
		return x.ToParties
	}
	return nil
}

func (x *SigningMessage) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SigningMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SigningMessage) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

type SigningMessageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutgoingMessages []*SigningMessage      `protobuf:"bytes,3,rep,name=outgoing_messages,json=outgoingMessages,proto3" json:"outgoing_messages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SigningMessageResponse) Reset() {
	*x = SigningMessageResponse{}
	mi := &file_proto_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningMessageResponse) ProtoMessage() {}

func (x *SigningMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningMessageResponse.ProtoReflect.Descriptor instead.
func (*SigningMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{15}
}

func (x *SigningMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SigningMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SigningMessageResponse) GetOutgoingMessages() []*SigningMessage {
	if x != nil {
		return x.OutgoingMessages
	}
	return nil
}

type GetSigningResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningResultRequest) Reset() {
	*x = GetSigningResultRequest{}
	mi := &file_proto_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningResultRequest) ProtoMessage() {}

func (x *GetSigningResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningResultRequest.ProtoReflect.Descriptor instead.
func (*GetSigningResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{16}
}

func (x *GetSigningResultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSigningResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Completed     bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Result        *SigningResult         `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningResultResponse) Reset() {
	*x = GetSigningResultResponse{}
	mi := &file_proto_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningResultResponse) ProtoMessage() {}

func (x *GetSigningResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningResultResponse.ProtoReflect.Descriptor instead.
func (*GetSigningResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{17}
}

func (x *GetSigningResultResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *GetSigningResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSigningResultResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetSigningResultResponse) GetResult() *SigningResult {
	if x != nil {
		return x.Result
	}
	return nil
}

type SigningResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"` // полная подпись в hex
	R             string                 `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
	S             string                 `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
	V             int32                  `protobuf:"varint,4,opt,name=v,proto3" json:"v,omitempty"` // recovery id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningResult) Reset() {
	*x = SigningResult{}
	mi := &file_proto_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningResult) ProtoMessage() {}

func (x *SigningResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningResult.ProtoReflect.Descriptor instead.
func (*SigningResult) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{18}
}

func (x *SigningResult) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SigningResult) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *SigningResult) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *SigningResult) GetV() int32 {
	if x != nil {
		return x.V
	}
	return 0
}

type MPCStreamMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromParty string                 `protobuf:"bytes,2,opt,name=from_party,json=fromParty,proto3" json:"from_party,omitempty"`
	ToParties []string               `protobuf:"bytes,3,rep,name=to_parties,json=toParties,proto3" json:"to_parties,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*MPCStreamMessage_Keygen
	//	*MPCStreamMessage_Signing
	//	*MPCStreamMessage_Control
	MessageType   isMPCStreamMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPCStreamMessage) Reset() {
	*x = MPCStreamMessage{}
	mi := &file_proto_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPCStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPCStreamMessage) ProtoMessage() {}

func (x *MPCStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPCStreamMessage.ProtoReflect.Descriptor instead.
func (*MPCStreamMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{19}
}

func (x *MPCStreamMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MPCStreamMessage) GetFromParty() string {
	if x != nil {
		return x.FromParty
	}
	return ""
}

func (x *MPCStreamMessage) GetToParties() []string {
	if x != nil {
		return x.ToParties
	}
	return nil
}

func (x *MPCStreamMessage) GetMessageType() isMPCStreamMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *MPCStreamMessage) GetKeygen() *KeygenStreamPayload {
	if x != nil {
		if x, ok := x.MessageType.(*MPCStreamMessage_Keygen); ok {
			return x.Keygen
		}
	}
	return nil
}

func (x *MPCStreamMessage) GetSigning() *SigningStreamPayload {
	if x != nil {
		if x, ok := x.MessageType.(*MPCStreamMessage_Signing); ok {
			return x.Signing
		}
	}
	return nil
}

func (x *MPCStreamMessage) GetControl() *ControlMessage {
	if x != nil {
		if x, ok := x.MessageType.(*MPCStreamMessage_Control); ok {
			return x.Control
		}
	}
	return nil
}

type isMPCStreamMessage_MessageType interface {
	isMPCStreamMessage_MessageType()
}

type MPCStreamMessage_Keygen struct {
	Keygen *KeygenStreamPayload `protobuf:"bytes,4,opt,name=keygen,proto3,oneof"`
}

type MPCStreamMessage_Signing struct {
	Signing *SigningStreamPayload `protobuf:"bytes,5,opt,name=signing,proto3,oneof"`
}

type MPCStreamMessage_Control struct {
	Control *ControlMessage `protobuf:"bytes,6,opt,name=control,proto3,oneof"`
}

func (*MPCStreamMessage_Keygen) isMPCStreamMessage_MessageType() {}

func (*MPCStreamMessage_Signing) isMPCStreamMessage_MessageType() {}

func (*MPCStreamMessage_Control) isMPCStreamMessage_MessageType() {}

type KeygenStreamPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsBroadcast   bool                   `protobuf:"varint,3,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenStreamPayload) Reset() {
	*x = KeygenStreamPayload{}
	mi := &file_proto_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenStreamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenStreamPayload) ProtoMessage() {}

func (x *KeygenStreamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenStreamPayload.ProtoReflect.Descriptor instead.
func (*KeygenStreamPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{20}
}

func (x *KeygenStreamPayload) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *KeygenStreamPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *KeygenStreamPayload) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

type SigningStreamPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsBroadcast   bool                   `protobuf:"varint,3,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningStreamPayload) Reset() {
	*x = SigningStreamPayload{}
	mi := &file_proto_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningStreamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningStreamPayload) ProtoMessage() {}

func (x *SigningStreamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningStreamPayload.ProtoReflect.Descriptor instead.
func (*SigningStreamPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{21}
}

func (x *SigningStreamPayload) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SigningStreamPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SigningStreamPayload) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlType            `protobuf:"varint,1,opt,name=type,proto3,enum=mpcnode.ControlType" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{22}
}

func (x *ControlMessage) GetType() ControlType {
	if x != nil {
		return x.Type
	}
	return ControlType_CONTROL_TYPE_UNSPECIFIED
}

func (x *ControlMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

var File_proto_node_proto protoreflect.FileDescriptor

const file_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x10proto/node.proto\x12\ampcnode\"\x14\n" +
	"\x12HealthCheckRequest\"a\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x14\n" +
	"\x12GetNodeInfoRequest\"\xda\x01\n" +
	"\x13GetNodeInfoResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bparty_id\x18\x02 \x01(\tR\apartyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.mpcnode.NodeStatusR\x06status\x12)\n" +
	"\x10supported_curves\x18\x06 \x03(\tR\x0fsupportedCurves\"\x94\x01\n" +
	"\x11InitKeygenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\aparties\x18\x02 \x03(\v2\x12.mpcnode.PartyInfoR\aparties\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x05R\tthreshold\x12\x14\n" +
	"\x05curve\x18\x04 \x01(\tR\x05curve\"a\n" +
	"\tPartyInfo\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1f\n" +
	"\vparty_index\x18\x02 \x01(\x05R\n" +
	"partyIndex\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\"r\n" +
	"\x12InitKeygenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xbf\x01\n" +
	"\rKeygenMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"from_party\x18\x02 \x01(\tR\tfromParty\x12\x1d\n" +
	"\n" +
	"to_parties\x18\x03 \x03(\tR\ttoParties\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x05R\x05round\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12!\n" +
	"\fis_broadcast\x18\x06 \x01(\bR\visBroadcast\"\x9b\x01\n" +
	"\x15KeygenMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12C\n" +
	"\x11outgoing_messages\x18\x03 \x03(\v2\x16.mpcnode.KeygenMessageR\x10outgoingMessages\"7\n" +
	"\x16GetKeygenResultRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xea\x01\n" +
	"\x17GetKeygenResultResponse\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12-\n" +
	"\x06result\x18\x04 \x01(\v2\x15.mpcnode.KeygenResultR\x06result\x12C\n" +
	"\x11outgoing_messages\x18\x05 \x03(\v2\x16.mpcnode.KeygenMessageR\x10outgoingMessages\"\xce\x01\n" +
	"\fKeygenResult\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12!\n" +
	"\fpublic_share\x18\x03 \x01(\tR\vpublicShare\x12\x1f\n" +
	"\vparty_index\x18\x04 \x01(\x05R\n" +
	"partyIndex\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12#\n" +
	"\rtotal_parties\x18\x06 \x01(\x05R\ftotalParties\"\xa0\x01\n" +
	"\x12InitSigningRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12&\n" +
	"\x0fmessage_to_sign\x18\x03 \x01(\fR\rmessageToSign\x12,\n" +
	"\aparties\x18\x04 \x03(\v2\x12.mpcnode.PartyInfoR\aparties\"s\n" +
	"\x13InitSigningResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\xc0\x01\n" +
	"\x0eSigningMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"from_party\x18\x02 \x01(\tR\tfromParty\x12\x1d\n" +
	"\n" +
	"to_parties\x18\x03 \x03(\tR\ttoParties\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x05R\x05round\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12!\n" +
	"\fis_broadcast\x18\x06 \x01(\bR\visBroadcast\"\x9d\x01\n" +
	"\x16SigningMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12D\n" +
	"\x11outgoing_messages\x18\x03 \x03(\v2\x17.mpcnode.SigningMessageR\x10outgoingMessages\"8\n" +
	"\x17GetSigningResultRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xa7\x01\n" +
	"\x18GetSigningResultResponse\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12.\n" +
	"\x06result\x18\x04 \x01(\v2\x16.mpcnode.SigningResultR\x06result\"W\n" +
	"\rSigningResult\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\f\n" +
	"\x01r\x18\x02 \x01(\tR\x01r\x12\f\n" +
	"\x01s\x18\x03 \x01(\tR\x01s\x12\f\n" +
	"\x01v\x18\x04 \x01(\x05R\x01v\"\xa7\x02\n" +
	"\x10MPCStreamMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"from_party\x18\x02 \x01(\tR\tfromParty\x12\x1d\n" +
	"\n" +
	"to_parties\x18\x03 \x03(\tR\ttoParties\x126\n" +
	"\x06keygen\x18\x04 \x01(\v2\x1c.mpcnode.KeygenStreamPayloadH\x00R\x06keygen\x129\n" +
	"\asigning\x18\x05 \x01(\v2\x1d.mpcnode.SigningStreamPayloadH\x00R\asigning\x123\n" +
	"\acontrol\x18\x06 \x01(\v2\x17.mpcnode.ControlMessageH\x00R\acontrolB\x0e\n" +
	"\fmessage_type\"b\n" +
	"\x13KeygenStreamPayload\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fis_broadcast\x18\x03 \x01(\bR\visBroadcast\"c\n" +
	"\x14SigningStreamPayload\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fis_broadcast\x18\x03 \x01(\bR\visBroadcast\"T\n" +
	"\x0eControlMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.mpcnode.ControlTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload*\x87\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x01\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x02\x12\x14\n" +
	"\x10NODE_STATUS_BUSY\x10\x03\x12\x15\n" +
	"\x11NODE_STATUS_ERROR\x10\x04*\x9d\x01\n" +
	"\vControlType\x12\x1c\n" +
	"\x18CONTROL_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONTROL_TYPE_SESSION_START\x10\x01\x12\x1c\n" +
	"\x18CONTROL_TYPE_SESSION_END\x10\x02\x12\x16\n" +
	"\x12CONTROL_TYPE_ERROR\x10\x03\x12\x1a\n" +
	"\x16CONTROL_TYPE_HEARTBEAT\x10\x042\xd5\x05\n" +
	"\x0eMPCNodeService\x12H\n" +
	"\vHealthCheck\x12\x1b.mpcnode.HealthCheckRequest\x1a\x1c.mpcnode.HealthCheckResponse\x12H\n" +
	"\vGetNodeInfo\x12\x1b.mpcnode.GetNodeInfoRequest\x1a\x1c.mpcnode.GetNodeInfoResponse\x12E\n" +
	"\n" +
	"InitKeygen\x12\x1a.mpcnode.InitKeygenRequest\x1a\x1b.mpcnode.InitKeygenResponse\x12N\n" +
	"\x14ProcessKeygenMessage\x12\x16.mpcnode.KeygenMessage\x1a\x1e.mpcnode.KeygenMessageResponse\x12T\n" +
	"\x0fGetKeygenResult\x12\x1f.mpcnode.GetKeygenResultRequest\x1a .mpcnode.GetKeygenResultResponse\x12H\n" +
	"\vInitSigning\x12\x1b.mpcnode.InitSigningRequest\x1a\x1c.mpcnode.InitSigningResponse\x12Q\n" +
	"\x15ProcessSigningMessage\x12\x17.mpcnode.SigningMessage\x1a\x1f.mpcnode.SigningMessageResponse\x12W\n" +
	"\x10GetSigningResult\x12 .mpcnode.GetSigningResultRequest\x1a!.mpcnode.GetSigningResultResponse\x12L\n" +
	"\x10MPCMessageStream\x12\x19.mpcnode.MPCStreamMessage\x1a\x19.mpcnode.MPCStreamMessage(\x010\x01B\x1fZ\x1dgithub.com/mpc_hsm/node/protob\x06proto3"

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData []byte
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)))
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_proto_node_proto_goTypes = []any{
	(NodeStatus)(0),                  // 0: mpcnode.NodeStatus
	(ControlType)(0),                 // 1: mpcnode.ControlType
	(*HealthCheckRequest)(nil),       // 2: mpcnode.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 3: mpcnode.HealthCheckResponse
	(*GetNodeInfoRequest)(nil),       // 4: mpcnode.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),      // 5: mpcnode.GetNodeInfoResponse
	(*InitKeygenRequest)(nil),        // 6: mpcnode.InitKeygenRequest
	(*PartyInfo)(nil),                // 7: mpcnode.PartyInfo
	(*InitKeygenResponse)(nil),       // 8: mpcnode.InitKeygenResponse
	(*KeygenMessage)(nil),            // 9: mpcnode.KeygenMessage
	(*KeygenMessageResponse)(nil),    // 10: mpcnode.KeygenMessageResponse
	(*GetKeygenResultRequest)(nil),   // 11: mpcnode.GetKeygenResultRequest
	(*GetKeygenResultResponse)(nil),  // 12: mpcnode.GetKeygenResultResponse
	(*KeygenResult)(nil),             // 13: mpcnode.KeygenResult
	(*InitSigningRequest)(nil),       // 14: mpcnode.InitSigningRequest
	(*InitSigningResponse)(nil),      // 15: mpcnode.InitSigningResponse
	(*SigningMessage)(nil),           // 16: mpcnode.SigningMessage
	(*SigningMessageResponse)(nil),   // 17: mpcnode.SigningMessageResponse
	(*GetSigningResultRequest)(nil),  // 18: mpcnode.GetSigningResultRequest
	(*GetSigningResultResponse)(nil), // 19: mpcnode.GetSigningResultResponse
	(*SigningResult)(nil),            // 20: mpcnode.SigningResult
	(*MPCStreamMessage)(nil),         // 21: mpcnode.MPCStreamMessage
	(*KeygenStreamPayload)(nil),      // 22: mpcnode.KeygenStreamPayload
	(*SigningStreamPayload)(nil),     // 23: mpcnode.SigningStreamPayload
	(*ControlMessage)(nil),           // 24: mpcnode.ControlMessage
}
var file_proto_node_proto_depIdxs = []int32{
	0,  // 0: mpcnode.GetNodeInfoResponse.status:type_name -> mpcnode.NodeStatus
	7,  // 1: mpcnode.InitKeygenRequest.parties:type_name -> mpcnode.PartyInfo
	9,  // 2: mpcnode.KeygenMessageResponse.outgoing_messages:type_name -> mpcnode.KeygenMessage
	13, // 3: mpcnode.GetKeygenResultResponse.result:type_name -> mpcnode.KeygenResult
	9,  // 4: mpcnode.GetKeygenResultResponse.outgoing_messages:type_name -> mpcnode.KeygenMessage
	7,  // 5: mpcnode.InitSigningRequest.parties:type_name -> mpcnode.PartyInfo
	16, // 6: mpcnode.SigningMessageResponse.outgoing_messages:type_name -> mpcnode.SigningMessage
	20, // 7: mpcnode.GetSigningResultResponse.result:type_name -> mpcnode.SigningResult
	22, // 8: mpcnode.MPCStreamMessage.keygen:type_name -> mpcnode.KeygenStreamPayload
	23, // 9: mpcnode.MPCStreamMessage.signing:type_name -> mpcnode.SigningStreamPayload
	24, // 10: mpcnode.MPCStreamMessage.control:type_name -> mpcnode.ControlMessage
	1,  // 11: mpcnode.ControlMessage.type:type_name -> mpcnode.ControlType
	2,  // 12: mpcnode.MPCNodeService.HealthCheck:input_type -> mpcnode.HealthCheckRequest
	4,  // 13: mpcnode.MPCNodeService.GetNodeInfo:input_type -> mpcnode.GetNodeInfoRequest
	6,  // 14: mpcnode.MPCNodeService.InitKeygen:input_type -> mpcnode.InitKeygenRequest
	9,  // 15: mpcnode.MPCNodeService.ProcessKeygenMessage:input_type -> mpcnode.KeygenMessage
	11, // 16: mpcnode.MPCNodeService.GetKeygenResult:input_type -> mpcnode.GetKeygenResultRequest
	14, // 17: mpcnode.MPCNodeService.InitSigning:input_type -> mpcnode.InitSigningRequest
	16, // 18: mpcnode.MPCNodeService.ProcessSigningMessage:input_type -> mpcnode.SigningMessage
	18, // 19: mpcnode.MPCNodeService.GetSigningResult:input_type -> mpcnode.GetSigningResultRequest
	21, // 20: mpcnode.MPCNodeService.MPCMessageStream:input_type -> mpcnode.MPCStreamMessage
	3,  // 21: mpcnode.MPCNodeService.HealthCheck:output_type -> mpcnode.HealthCheckResponse
	5,  // 22: mpcnode.MPCNodeService.GetNodeInfo:output_type -> mpcnode.GetNodeInfoResponse
	8,  // 23: mpcnode.MPCNodeService.InitKeygen:output_type -> mpcnode.InitKeygenResponse
	10, // 24: mpcnode.MPCNodeService.ProcessKeygenMessage:output_type -> mpcnode.KeygenMessageResponse
	12, // 25: mpcnode.MPCNodeService.GetKeygenResult:output_type -> mpcnode.GetKeygenResultResponse
	15, // 26: mpcnode.MPCNodeService.InitSigning:output_type -> mpcnode.InitSigningResponse
	17, // 27: mpcnode.MPCNodeService.ProcessSigningMessage:output_type -> mpcnode.SigningMessageResponse
	19, // 28: mpcnode.MPCNodeService.GetSigningResult:output_type -> mpcnode.GetSigningResultResponse
	21, // 29: mpcnode.MPCNodeService.MPCMessageStream:output_type -> mpcnode.MPCStreamMessage
	21, // [21:30] is the sub-list for method output_type
	12, // [12:21] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	file_proto_node_proto_msgTypes[19].OneofWrappers = []any{
		(*MPCStreamMessage_Keygen)(nil),
		(*MPCStreamMessage_Signing)(nil),
		(*MPCStreamMessage_Control)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		EnumInfos:         file_proto_node_proto_enumTypes,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
