// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.12.4
// source: proto/node.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NodeStatus int32

const (
	NodeStatus_NODE_STATUS_UNSPECIFIED NodeStatus = 0
	NodeStatus_NODE_STATUS_ONLINE      NodeStatus = 1
	NodeStatus_NODE_STATUS_OFFLINE     NodeStatus = 2
	NodeStatus_NODE_STATUS_BUSY        NodeStatus = 3
	NodeStatus_NODE_STATUS_ERROR       NodeStatus = 4
)

// Enum value maps for NodeStatus.
var (
	NodeStatus_name = map[int32]string{
		0: "NODE_STATUS_UNSPECIFIED",
		1: "NODE_STATUS_ONLINE",
		2: "NODE_STATUS_OFFLINE",
		3: "NODE_STATUS_BUSY",
		4: "NODE_STATUS_ERROR",
	}
	NodeStatus_value = map[string]int32{
		"NODE_STATUS_UNSPECIFIED": 0,
		"NODE_STATUS_ONLINE":      1,
		"NODE_STATUS_OFFLINE":     2,
		"NODE_STATUS_BUSY":        3,
		"NODE_STATUS_ERROR":       4,
	}
)

func (x NodeStatus) Enum() *NodeStatus {
	p := new(NodeStatus)
	*p = x
	return p
}

func (x NodeStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NodeStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[0].Descriptor()
}

func (NodeStatus) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[0]
}

func (x NodeStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NodeStatus.Descriptor instead.
func (NodeStatus) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

type ControlType int32

const (
	ControlType_CONTROL_TYPE_UNSPECIFIED   ControlType = 0
	ControlType_CONTROL_TYPE_SESSION_START ControlType = 1
	ControlType_CONTROL_TYPE_SESSION_END   ControlType = 2
	ControlType_CONTROL_TYPE_ERROR         ControlType = 3
	ControlType_CONTROL_TYPE_HEARTBEAT     ControlType = 4
)

// Enum value maps for ControlType.
var (
	ControlType_name = map[int32]string{
		0: "CONTROL_TYPE_UNSPECIFIED",
		1: "CONTROL_TYPE_SESSION_START",
		2: "CONTROL_TYPE_SESSION_END",
		3: "CONTROL_TYPE_ERROR",
		4: "CONTROL_TYPE_HEARTBEAT",
	}
	ControlType_value = map[string]int32{
		"CONTROL_TYPE_UNSPECIFIED":   0,
		"CONTROL_TYPE_SESSION_START": 1,
		"CONTROL_TYPE_SESSION_END":   2,
		"CONTROL_TYPE_ERROR":         3,
		"CONTROL_TYPE_HEARTBEAT":     4,
	}
)

func (x ControlType) Enum() *ControlType {
	p := new(ControlType)
	*p = x
	return p
}

func (x ControlType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ControlType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[1].Descriptor()
}

func (ControlType) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[1]
}

func (x ControlType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ControlType.Descriptor instead.
func (ControlType) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

type SessionType int32

const (
	SessionType_SESSION_TYPE_UNSPECIFIED SessionType = 0
	SessionType_SESSION_TYPE_KEYGEN      SessionType = 1
	SessionType_SESSION_TYPE_SIGNING     SessionType = 2
	SessionType_SESSION_TYPE_RESHARING   SessionType = 3
)

// Enum value maps for SessionType.
var (
	SessionType_name = map[int32]string{
		0: "SESSION_TYPE_UNSPECIFIED",
		1: "SESSION_TYPE_KEYGEN",
		2: "SESSION_TYPE_SIGNING",
		3: "SESSION_TYPE_RESHARING",
	}
	SessionType_value = map[string]int32{
		"SESSION_TYPE_UNSPECIFIED": 0,
		"SESSION_TYPE_KEYGEN":      1,
		"SESSION_TYPE_SIGNING":     2,
		"SESSION_TYPE_RESHARING":   3,
	}
)

func (x SessionType) Enum() *SessionType {
	p := new(SessionType)
	*p = x
	return p
}

func (x SessionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SessionType) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_node_proto_enumTypes[2].Descriptor()
}

func (SessionType) Type() protoreflect.EnumType {
	return &file_proto_node_proto_enumTypes[2]
}

func (x SessionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SessionType.Descriptor instead.
func (SessionType) EnumDescriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

// SignedEnvelope оборачивает любое сообщение с криптографической подписью
type SignedEnvelope struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       []byte                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`                                    // Сериализованное оригинальное сообщение
	SignerPartyId string                 `protobuf:"bytes,2,opt,name=signer_party_id,json=signerPartyId,proto3" json:"signer_party_id,omitempty"` // PartyID подписавшего
	Signature     []byte                 `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`                                // Ed25519 подпись
	Timestamp     int64                  `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                               // Unix timestamp в наносекундах
	Nonce         []byte                 `protobuf:"bytes,5,opt,name=nonce,proto3" json:"nonce,omitempty"`                                        // 16 байт случайных данных (защита от replay)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignedEnvelope) Reset() {
	*x = SignedEnvelope{}
	mi := &file_proto_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedEnvelope) ProtoMessage() {}

func (x *SignedEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedEnvelope.ProtoReflect.Descriptor instead.
func (*SignedEnvelope) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{0}
}

func (x *SignedEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SignedEnvelope) GetSignerPartyId() string {
	if x != nil {
		return x.SignerPartyId
	}
	return ""
}

func (x *SignedEnvelope) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SignedEnvelope) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SignedEnvelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type HealthCheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckRequest) Reset() {
	*x = HealthCheckRequest{}
	mi := &file_proto_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckRequest) ProtoMessage() {}

func (x *HealthCheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckRequest.ProtoReflect.Descriptor instead.
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{1}
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Healthy       bool                   `protobuf:"varint,1,opt,name=healthy,proto3" json:"healthy,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_proto_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{2}
}

func (x *HealthCheckResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

func (x *HealthCheckResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthCheckResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type GetNodeInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNodeInfoRequest) Reset() {
	*x = GetNodeInfoRequest{}
	mi := &file_proto_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoRequest) ProtoMessage() {}

func (x *GetNodeInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoRequest.ProtoReflect.Descriptor instead.
func (*GetNodeInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{3}
}

type GetNodeInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	NodeId           string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PartyId          string                 `protobuf:"bytes,2,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	PublicKey        string                 `protobuf:"bytes,3,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"` // TSS публичный ключ
	Address          string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Status           NodeStatus             `protobuf:"varint,5,opt,name=status,proto3,enum=mpcnode.NodeStatus" json:"status,omitempty"`
	SupportedCurves  []string               `protobuf:"bytes,6,rep,name=supported_curves,json=supportedCurves,proto3" json:"supported_curves,omitempty"`
	SigningPublicKey string                 `protobuf:"bytes,7,opt,name=signing_public_key,json=signingPublicKey,proto3" json:"signing_public_key,omitempty"` // Ed25519 публичный ключ для верификации подписей (base64)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetNodeInfoResponse) Reset() {
	*x = GetNodeInfoResponse{}
	mi := &file_proto_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNodeInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNodeInfoResponse) ProtoMessage() {}

func (x *GetNodeInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNodeInfoResponse.ProtoReflect.Descriptor instead.
func (*GetNodeInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{4}
}

func (x *GetNodeInfoResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *GetNodeInfoResponse) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *GetNodeInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *GetNodeInfoResponse) GetStatus() NodeStatus {
	if x != nil {
		return x.Status
	}
	return NodeStatus_NODE_STATUS_UNSPECIFIED
}

func (x *GetNodeInfoResponse) GetSupportedCurves() []string {
	if x != nil {
		return x.SupportedCurves
	}
	return nil
}

func (x *GetNodeInfoResponse) GetSigningPublicKey() string {
	if x != nil {
		return x.SigningPublicKey
	}
	return ""
}

type InitKeygenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Parties       []*PartyInfo           `protobuf:"bytes,2,rep,name=parties,proto3" json:"parties,omitempty"`
	Threshold     int32                  `protobuf:"varint,3,opt,name=threshold,proto3" json:"threshold,omitempty"`
	Curve         string                 `protobuf:"bytes,4,opt,name=curve,proto3" json:"curve,omitempty"` // secp256k1, ed25519, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitKeygenRequest) Reset() {
	*x = InitKeygenRequest{}
	mi := &file_proto_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitKeygenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitKeygenRequest) ProtoMessage() {}

func (x *InitKeygenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitKeygenRequest.ProtoReflect.Descriptor instead.
func (*InitKeygenRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{5}
}

func (x *InitKeygenRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitKeygenRequest) GetParties() []*PartyInfo {
	if x != nil {
		return x.Parties
	}
	return nil
}

func (x *InitKeygenRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *InitKeygenRequest) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

type PartyInfo struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PartyId          string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	PartyIndex       int32                  `protobuf:"varint,2,opt,name=party_index,json=partyIndex,proto3" json:"party_index,omitempty"`
	Address          string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	SigningPublicKey string                 `protobuf:"bytes,4,opt,name=signing_public_key,json=signingPublicKey,proto3" json:"signing_public_key,omitempty"` // Ed25519 публичный ключ участника (base64)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PartyInfo) Reset() {
	*x = PartyInfo{}
	mi := &file_proto_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PartyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PartyInfo) ProtoMessage() {}

func (x *PartyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PartyInfo.ProtoReflect.Descriptor instead.
func (*PartyInfo) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{6}
}

func (x *PartyInfo) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PartyInfo) GetPartyIndex() int32 {
	if x != nil {
		return x.PartyIndex
	}
	return 0
}

func (x *PartyInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PartyInfo) GetSigningPublicKey() string {
	if x != nil {
		return x.SigningPublicKey
	}
	return ""
}

type InitKeygenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitKeygenResponse) Reset() {
	*x = InitKeygenResponse{}
	mi := &file_proto_node_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitKeygenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitKeygenResponse) ProtoMessage() {}

func (x *InitKeygenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitKeygenResponse.ProtoReflect.Descriptor instead.
func (*InitKeygenResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{7}
}

func (x *InitKeygenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitKeygenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InitKeygenResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type KeygenMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SessionId   string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromParty   string                 `protobuf:"bytes,2,opt,name=from_party,json=fromParty,proto3" json:"from_party,omitempty"`
	ToParties   []string               `protobuf:"bytes,3,rep,name=to_parties,json=toParties,proto3" json:"to_parties,omitempty"` // пусто = broadcast
	Round       int32                  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Payload     []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	IsBroadcast bool                   `protobuf:"varint,6,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	// Поля безопасности (обязательные)
	Signature     []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`  // Ed25519 подпись (session_id || from_party || round || payload || timestamp || nonce)
	Timestamp     int64  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp в наносекундах
	Nonce         []byte `protobuf:"bytes,9,opt,name=nonce,proto3" json:"nonce,omitempty"`          // 16 байт случайных данных
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenMessage) Reset() {
	*x = KeygenMessage{}
	mi := &file_proto_node_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenMessage) ProtoMessage() {}

func (x *KeygenMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenMessage.ProtoReflect.Descriptor instead.
func (*KeygenMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{8}
}

func (x *KeygenMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *KeygenMessage) GetFromParty() string {
	if x != nil {
		return x.FromParty
	}
	return ""
}

func (x *KeygenMessage) GetToParties() []string {
	if x != nil {
		return x.ToParties
	}
	return nil
}

func (x *KeygenMessage) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *KeygenMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *KeygenMessage) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

func (x *KeygenMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *KeygenMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *KeygenMessage) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type KeygenMessageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutgoingMessages []*KeygenMessage       `protobuf:"bytes,3,rep,name=outgoing_messages,json=outgoingMessages,proto3" json:"outgoing_messages,omitempty"` // исходящие сообщения для других участников
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *KeygenMessageResponse) Reset() {
	*x = KeygenMessageResponse{}
	mi := &file_proto_node_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenMessageResponse) ProtoMessage() {}

func (x *KeygenMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenMessageResponse.ProtoReflect.Descriptor instead.
func (*KeygenMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{9}
}

func (x *KeygenMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *KeygenMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *KeygenMessageResponse) GetOutgoingMessages() []*KeygenMessage {
	if x != nil {
		return x.OutgoingMessages
	}
	return nil
}

type GetKeygenResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeygenResultRequest) Reset() {
	*x = GetKeygenResultRequest{}
	mi := &file_proto_node_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeygenResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeygenResultRequest) ProtoMessage() {}

func (x *GetKeygenResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeygenResultRequest.ProtoReflect.Descriptor instead.
func (*GetKeygenResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{10}
}

func (x *GetKeygenResultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetKeygenResultResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Completed        bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Result           *KeygenResult          `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	OutgoingMessages []*KeygenMessage       `protobuf:"bytes,5,rep,name=outgoing_messages,json=outgoingMessages,proto3" json:"outgoing_messages,omitempty"` // исходящие сообщения для маршрутизации
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetKeygenResultResponse) Reset() {
	*x = GetKeygenResultResponse{}
	mi := &file_proto_node_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeygenResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeygenResultResponse) ProtoMessage() {}

func (x *GetKeygenResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeygenResultResponse.ProtoReflect.Descriptor instead.
func (*GetKeygenResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{11}
}

func (x *GetKeygenResultResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *GetKeygenResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetKeygenResultResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetKeygenResultResponse) GetResult() *KeygenResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetKeygenResultResponse) GetOutgoingMessages() []*KeygenMessage {
	if x != nil {
		return x.OutgoingMessages
	}
	return nil
}

type KeygenResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PublicKey     string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`                            // Ethereum/Bitcoin адрес
	PublicShare   string                 `protobuf:"bytes,3,opt,name=public_share,json=publicShare,proto3" json:"public_share,omitempty"` // публичная часть доли ключа
	PartyIndex    int32                  `protobuf:"varint,4,opt,name=party_index,json=partyIndex,proto3" json:"party_index,omitempty"`
	Threshold     int32                  `protobuf:"varint,5,opt,name=threshold,proto3" json:"threshold,omitempty"`
	TotalParties  int32                  `protobuf:"varint,6,opt,name=total_parties,json=totalParties,proto3" json:"total_parties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenResult) Reset() {
	*x = KeygenResult{}
	mi := &file_proto_node_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenResult) ProtoMessage() {}

func (x *KeygenResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenResult.ProtoReflect.Descriptor instead.
func (*KeygenResult) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{12}
}

func (x *KeygenResult) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *KeygenResult) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *KeygenResult) GetPublicShare() string {
	if x != nil {
		return x.PublicShare
	}
	return ""
}

func (x *KeygenResult) GetPartyIndex() int32 {
	if x != nil {
		return x.PartyIndex
	}
	return 0
}

func (x *KeygenResult) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *KeygenResult) GetTotalParties() int32 {
	if x != nil {
		return x.TotalParties
	}
	return 0
}

type InitSigningRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	KeyId         string                 `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"` // ID ключа для подписания
	MessageToSign []byte                 `protobuf:"bytes,3,opt,name=message_to_sign,json=messageToSign,proto3" json:"message_to_sign,omitempty"`
	Parties       []*PartyInfo           `protobuf:"bytes,4,rep,name=parties,proto3" json:"parties,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSigningRequest) Reset() {
	*x = InitSigningRequest{}
	mi := &file_proto_node_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSigningRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSigningRequest) ProtoMessage() {}

func (x *InitSigningRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSigningRequest.ProtoReflect.Descriptor instead.
func (*InitSigningRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{13}
}

func (x *InitSigningRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *InitSigningRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *InitSigningRequest) GetMessageToSign() []byte {
	if x != nil {
		return x.MessageToSign
	}
	return nil
}

func (x *InitSigningRequest) GetParties() []*PartyInfo {
	if x != nil {
		return x.Parties
	}
	return nil
}

type InitSigningResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	SessionId     string                 `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitSigningResponse) Reset() {
	*x = InitSigningResponse{}
	mi := &file_proto_node_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitSigningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitSigningResponse) ProtoMessage() {}

func (x *InitSigningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitSigningResponse.ProtoReflect.Descriptor instead.
func (*InitSigningResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{14}
}

func (x *InitSigningResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitSigningResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *InitSigningResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type SigningMessage struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	SessionId   string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromParty   string                 `protobuf:"bytes,2,opt,name=from_party,json=fromParty,proto3" json:"from_party,omitempty"`
	ToParties   []string               `protobuf:"bytes,3,rep,name=to_parties,json=toParties,proto3" json:"to_parties,omitempty"`
	Round       int32                  `protobuf:"varint,4,opt,name=round,proto3" json:"round,omitempty"`
	Payload     []byte                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	IsBroadcast bool                   `protobuf:"varint,6,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	// Поля безопасности (обязательные)
	Signature     []byte `protobuf:"bytes,7,opt,name=signature,proto3" json:"signature,omitempty"`  // Ed25519 подпись
	Timestamp     int64  `protobuf:"varint,8,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // Unix timestamp в наносекундах
	Nonce         []byte `protobuf:"bytes,9,opt,name=nonce,proto3" json:"nonce,omitempty"`          // 16 байт случайных данных
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningMessage) Reset() {
	*x = SigningMessage{}
	mi := &file_proto_node_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningMessage) ProtoMessage() {}

func (x *SigningMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningMessage.ProtoReflect.Descriptor instead.
func (*SigningMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{15}
}

func (x *SigningMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SigningMessage) GetFromParty() string {
	if x != nil {
		return x.FromParty
	}
	return ""
}

func (x *SigningMessage) GetToParties() []string {
	if x != nil {
		return x.ToParties
	}
	return nil
}

func (x *SigningMessage) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SigningMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *SigningMessage) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

func (x *SigningMessage) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

func (x *SigningMessage) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SigningMessage) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type SigningMessageResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutgoingMessages []*SigningMessage      `protobuf:"bytes,3,rep,name=outgoing_messages,json=outgoingMessages,proto3" json:"outgoing_messages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SigningMessageResponse) Reset() {
	*x = SigningMessageResponse{}
	mi := &file_proto_node_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningMessageResponse) ProtoMessage() {}

func (x *SigningMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningMessageResponse.ProtoReflect.Descriptor instead.
func (*SigningMessageResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{16}
}

func (x *SigningMessageResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SigningMessageResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SigningMessageResponse) GetOutgoingMessages() []*SigningMessage {
	if x != nil {
		return x.OutgoingMessages
	}
	return nil
}

type GetSigningResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSigningResultRequest) Reset() {
	*x = GetSigningResultRequest{}
	mi := &file_proto_node_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningResultRequest) ProtoMessage() {}

func (x *GetSigningResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningResultRequest.ProtoReflect.Descriptor instead.
func (*GetSigningResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{17}
}

func (x *GetSigningResultRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type GetSigningResultResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Completed        bool                   `protobuf:"varint,1,opt,name=completed,proto3" json:"completed,omitempty"`
	Success          bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	Result           *SigningResult         `protobuf:"bytes,4,opt,name=result,proto3" json:"result,omitempty"`
	OutgoingMessages []*SigningMessage      `protobuf:"bytes,5,rep,name=outgoing_messages,json=outgoingMessages,proto3" json:"outgoing_messages,omitempty"` // исходящие сообщения для маршрутизации
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetSigningResultResponse) Reset() {
	*x = GetSigningResultResponse{}
	mi := &file_proto_node_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSigningResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigningResultResponse) ProtoMessage() {}

func (x *GetSigningResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigningResultResponse.ProtoReflect.Descriptor instead.
func (*GetSigningResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{18}
}

func (x *GetSigningResultResponse) GetCompleted() bool {
	if x != nil {
		return x.Completed
	}
	return false
}

func (x *GetSigningResultResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetSigningResultResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *GetSigningResultResponse) GetResult() *SigningResult {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *GetSigningResultResponse) GetOutgoingMessages() []*SigningMessage {
	if x != nil {
		return x.OutgoingMessages
	}
	return nil
}

type SigningResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Signature     string                 `protobuf:"bytes,1,opt,name=signature,proto3" json:"signature,omitempty"` // полная подпись в hex
	R             string                 `protobuf:"bytes,2,opt,name=r,proto3" json:"r,omitempty"`
	S             string                 `protobuf:"bytes,3,opt,name=s,proto3" json:"s,omitempty"`
	V             int32                  `protobuf:"varint,4,opt,name=v,proto3" json:"v,omitempty"` // recovery id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningResult) Reset() {
	*x = SigningResult{}
	mi := &file_proto_node_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningResult) ProtoMessage() {}

func (x *SigningResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningResult.ProtoReflect.Descriptor instead.
func (*SigningResult) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{19}
}

func (x *SigningResult) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SigningResult) GetR() string {
	if x != nil {
		return x.R
	}
	return ""
}

func (x *SigningResult) GetS() string {
	if x != nil {
		return x.S
	}
	return ""
}

func (x *SigningResult) GetV() int32 {
	if x != nil {
		return x.V
	}
	return 0
}

type MPCStreamMessage struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	FromParty string                 `protobuf:"bytes,2,opt,name=from_party,json=fromParty,proto3" json:"from_party,omitempty"`
	ToParties []string               `protobuf:"bytes,3,rep,name=to_parties,json=toParties,proto3" json:"to_parties,omitempty"`
	// Types that are valid to be assigned to MessageType:
	//
	//	*MPCStreamMessage_Keygen
	//	*MPCStreamMessage_Signing
	//	*MPCStreamMessage_Control
	MessageType   isMPCStreamMessage_MessageType `protobuf_oneof:"message_type"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MPCStreamMessage) Reset() {
	*x = MPCStreamMessage{}
	mi := &file_proto_node_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MPCStreamMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MPCStreamMessage) ProtoMessage() {}

func (x *MPCStreamMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MPCStreamMessage.ProtoReflect.Descriptor instead.
func (*MPCStreamMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{20}
}

func (x *MPCStreamMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *MPCStreamMessage) GetFromParty() string {
	if x != nil {
		return x.FromParty
	}
	return ""
}

func (x *MPCStreamMessage) GetToParties() []string {
	if x != nil {
		return x.ToParties
	}
	return nil
}

func (x *MPCStreamMessage) GetMessageType() isMPCStreamMessage_MessageType {
	if x != nil {
		return x.MessageType
	}
	return nil
}

func (x *MPCStreamMessage) GetKeygen() *KeygenStreamPayload {
	if x != nil {
		if x, ok := x.MessageType.(*MPCStreamMessage_Keygen); ok {
			return x.Keygen
		}
	}
	return nil
}

func (x *MPCStreamMessage) GetSigning() *SigningStreamPayload {
	if x != nil {
		if x, ok := x.MessageType.(*MPCStreamMessage_Signing); ok {
			return x.Signing
		}
	}
	return nil
}

func (x *MPCStreamMessage) GetControl() *ControlMessage {
	if x != nil {
		if x, ok := x.MessageType.(*MPCStreamMessage_Control); ok {
			return x.Control
		}
	}
	return nil
}

type isMPCStreamMessage_MessageType interface {
	isMPCStreamMessage_MessageType()
}

type MPCStreamMessage_Keygen struct {
	Keygen *KeygenStreamPayload `protobuf:"bytes,4,opt,name=keygen,proto3,oneof"`
}

type MPCStreamMessage_Signing struct {
	Signing *SigningStreamPayload `protobuf:"bytes,5,opt,name=signing,proto3,oneof"`
}

type MPCStreamMessage_Control struct {
	Control *ControlMessage `protobuf:"bytes,6,opt,name=control,proto3,oneof"`
}

func (*MPCStreamMessage_Keygen) isMPCStreamMessage_MessageType() {}

func (*MPCStreamMessage_Signing) isMPCStreamMessage_MessageType() {}

func (*MPCStreamMessage_Control) isMPCStreamMessage_MessageType() {}

type KeygenStreamPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsBroadcast   bool                   `protobuf:"varint,3,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeygenStreamPayload) Reset() {
	*x = KeygenStreamPayload{}
	mi := &file_proto_node_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeygenStreamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeygenStreamPayload) ProtoMessage() {}

func (x *KeygenStreamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeygenStreamPayload.ProtoReflect.Descriptor instead.
func (*KeygenStreamPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{21}
}

func (x *KeygenStreamPayload) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *KeygenStreamPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *KeygenStreamPayload) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

type SigningStreamPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Round         int32                  `protobuf:"varint,1,opt,name=round,proto3" json:"round,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsBroadcast   bool                   `protobuf:"varint,3,opt,name=is_broadcast,json=isBroadcast,proto3" json:"is_broadcast,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SigningStreamPayload) Reset() {
	*x = SigningStreamPayload{}
	mi := &file_proto_node_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SigningStreamPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigningStreamPayload) ProtoMessage() {}

func (x *SigningStreamPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigningStreamPayload.ProtoReflect.Descriptor instead.
func (*SigningStreamPayload) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{22}
}

func (x *SigningStreamPayload) GetRound() int32 {
	if x != nil {
		return x.Round
	}
	return 0
}

func (x *SigningStreamPayload) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *SigningStreamPayload) GetIsBroadcast() bool {
	if x != nil {
		return x.IsBroadcast
	}
	return false
}

type ControlMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ControlType            `protobuf:"varint,1,opt,name=type,proto3,enum=mpcnode.ControlType" json:"type,omitempty"`
	Payload       string                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_proto_node_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{23}
}

func (x *ControlMessage) GetType() ControlType {
	if x != nil {
		return x.Type
	}
	return ControlType_CONTROL_TYPE_UNSPECIFIED
}

func (x *ControlMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

// Ответ на подписанное keygen сообщение
type SignedKeygenResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutgoingMessages []*SignedEnvelope      `protobuf:"bytes,3,rep,name=outgoing_messages,json=outgoingMessages,proto3" json:"outgoing_messages,omitempty"` // Подписанные исходящие сообщения
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignedKeygenResponse) Reset() {
	*x = SignedKeygenResponse{}
	mi := &file_proto_node_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedKeygenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedKeygenResponse) ProtoMessage() {}

func (x *SignedKeygenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedKeygenResponse.ProtoReflect.Descriptor instead.
func (*SignedKeygenResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{24}
}

func (x *SignedKeygenResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignedKeygenResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SignedKeygenResponse) GetOutgoingMessages() []*SignedEnvelope {
	if x != nil {
		return x.OutgoingMessages
	}
	return nil
}

// Ответ на подписанное signing сообщение
type SignedSigningResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Success          bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	ErrorMessage     string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	OutgoingMessages []*SignedEnvelope      `protobuf:"bytes,3,rep,name=outgoing_messages,json=outgoingMessages,proto3" json:"outgoing_messages,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SignedSigningResponse) Reset() {
	*x = SignedSigningResponse{}
	mi := &file_proto_node_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignedSigningResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignedSigningResponse) ProtoMessage() {}

func (x *SignedSigningResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignedSigningResponse.ProtoReflect.Descriptor instead.
func (*SignedSigningResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{25}
}

func (x *SignedSigningResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SignedSigningResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SignedSigningResponse) GetOutgoingMessages() []*SignedEnvelope {
	if x != nil {
		return x.OutgoingMessages
	}
	return nil
}

// Запрос информации о пирах
type PeerInfoRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	RequesterPartyId   string                 `protobuf:"bytes,1,opt,name=requester_party_id,json=requesterPartyId,proto3" json:"requester_party_id,omitempty"`
	RequesterPublicKey string                 `protobuf:"bytes,2,opt,name=requester_public_key,json=requesterPublicKey,proto3" json:"requester_public_key,omitempty"` // Ed25519 публичный ключ (base64)
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PeerInfoRequest) Reset() {
	*x = PeerInfoRequest{}
	mi := &file_proto_node_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfoRequest) ProtoMessage() {}

func (x *PeerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfoRequest.ProtoReflect.Descriptor instead.
func (*PeerInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{26}
}

func (x *PeerInfoRequest) GetRequesterPartyId() string {
	if x != nil {
		return x.RequesterPartyId
	}
	return ""
}

func (x *PeerInfoRequest) GetRequesterPublicKey() string {
	if x != nil {
		return x.RequesterPublicKey
	}
	return ""
}

// Ответ с информацией о пирах
type PeerInfoResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PartyId          string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	SigningPublicKey string                 `protobuf:"bytes,2,opt,name=signing_public_key,json=signingPublicKey,proto3" json:"signing_public_key,omitempty"`
	Address          string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	KnownPeers       []*PeerRecord          `protobuf:"bytes,4,rep,name=known_peers,json=knownPeers,proto3" json:"known_peers,omitempty"` // Известные пиры для discovery
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerInfoResponse) Reset() {
	*x = PeerInfoResponse{}
	mi := &file_proto_node_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfoResponse) ProtoMessage() {}

func (x *PeerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfoResponse.ProtoReflect.Descriptor instead.
func (*PeerInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{27}
}

func (x *PeerInfoResponse) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PeerInfoResponse) GetSigningPublicKey() string {
	if x != nil {
		return x.SigningPublicKey
	}
	return ""
}

func (x *PeerInfoResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerInfoResponse) GetKnownPeers() []*PeerRecord {
	if x != nil {
		return x.KnownPeers
	}
	return nil
}

// Запись о пире
type PeerRecord struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PartyId          string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	SigningPublicKey string                 `protobuf:"bytes,2,opt,name=signing_public_key,json=signingPublicKey,proto3" json:"signing_public_key,omitempty"`
	Address          string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	LastSeen         int64                  `protobuf:"varint,4,opt,name=last_seen,json=lastSeen,proto3" json:"last_seen,omitempty"` // Unix timestamp
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PeerRecord) Reset() {
	*x = PeerRecord{}
	mi := &file_proto_node_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerRecord) ProtoMessage() {}

func (x *PeerRecord) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerRecord.ProtoReflect.Descriptor instead.
func (*PeerRecord) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{28}
}

func (x *PeerRecord) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PeerRecord) GetSigningPublicKey() string {
	if x != nil {
		return x.SigningPublicKey
	}
	return ""
}

func (x *PeerRecord) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *PeerRecord) GetLastSeen() int64 {
	if x != nil {
		return x.LastSeen
	}
	return 0
}

// Ping запрос
type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FromPartyId   string                 `protobuf:"bytes,1,opt,name=from_party_id,json=fromPartyId,proto3" json:"from_party_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_proto_node_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{29}
}

func (x *PingRequest) GetFromPartyId() string {
	if x != nil {
		return x.FromPartyId
	}
	return ""
}

func (x *PingRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Ping ответ
type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PartyId       string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Healthy       bool                   `protobuf:"varint,3,opt,name=healthy,proto3" json:"healthy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_proto_node_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{30}
}

func (x *PingResponse) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *PingResponse) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *PingResponse) GetHealthy() bool {
	if x != nil {
		return x.Healthy
	}
	return false
}

// Запрос на инициацию сессии (P2P)
type SessionInitRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	SessionId           string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	SessionType         SessionType            `protobuf:"varint,2,opt,name=session_type,json=sessionType,proto3,enum=mpcnode.SessionType" json:"session_type,omitempty"`
	ParticipantPartyIds []string               `protobuf:"bytes,3,rep,name=participant_party_ids,json=participantPartyIds,proto3" json:"participant_party_ids,omitempty"`
	Threshold           int32                  `protobuf:"varint,4,opt,name=threshold,proto3" json:"threshold,omitempty"`
	InitiatorPartyId    string                 `protobuf:"bytes,5,opt,name=initiator_party_id,json=initiatorPartyId,proto3" json:"initiator_party_id,omitempty"`
	InitiatorSignature  []byte                 `protobuf:"bytes,6,opt,name=initiator_signature,json=initiatorSignature,proto3" json:"initiator_signature,omitempty"` // Подпись инициатора
	Timestamp           int64                  `protobuf:"varint,7,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Curve               string                 `protobuf:"bytes,8,opt,name=curve,proto3" json:"curve,omitempty"`                                        // Для keygen
	MessageToSign       []byte                 `protobuf:"bytes,9,opt,name=message_to_sign,json=messageToSign,proto3" json:"message_to_sign,omitempty"` // Для signing
	KeyId               string                 `protobuf:"bytes,10,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`                          // Для signing
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SessionInitRequest) Reset() {
	*x = SessionInitRequest{}
	mi := &file_proto_node_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInitRequest) ProtoMessage() {}

func (x *SessionInitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInitRequest.ProtoReflect.Descriptor instead.
func (*SessionInitRequest) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{31}
}

func (x *SessionInitRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionInitRequest) GetSessionType() SessionType {
	if x != nil {
		return x.SessionType
	}
	return SessionType_SESSION_TYPE_UNSPECIFIED
}

func (x *SessionInitRequest) GetParticipantPartyIds() []string {
	if x != nil {
		return x.ParticipantPartyIds
	}
	return nil
}

func (x *SessionInitRequest) GetThreshold() int32 {
	if x != nil {
		return x.Threshold
	}
	return 0
}

func (x *SessionInitRequest) GetInitiatorPartyId() string {
	if x != nil {
		return x.InitiatorPartyId
	}
	return ""
}

func (x *SessionInitRequest) GetInitiatorSignature() []byte {
	if x != nil {
		return x.InitiatorSignature
	}
	return nil
}

func (x *SessionInitRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SessionInitRequest) GetCurve() string {
	if x != nil {
		return x.Curve
	}
	return ""
}

func (x *SessionInitRequest) GetMessageToSign() []byte {
	if x != nil {
		return x.MessageToSign
	}
	return nil
}

func (x *SessionInitRequest) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

// Ответ на запрос инициации сессии
type SessionInitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	PartyId       string                 `protobuf:"bytes,3,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,4,opt,name=signature,proto3" json:"signature,omitempty"` // Подпись подтверждения
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInitResponse) Reset() {
	*x = SessionInitResponse{}
	mi := &file_proto_node_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInitResponse) ProtoMessage() {}

func (x *SessionInitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInitResponse.ProtoReflect.Descriptor instead.
func (*SessionInitResponse) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{32}
}

func (x *SessionInitResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *SessionInitResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *SessionInitResponse) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *SessionInitResponse) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Команда старта сессии (после сбора ACK)
type SessionStartCommand struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	SessionId          string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Participants       []*SessionParticipant  `protobuf:"bytes,2,rep,name=participants,proto3" json:"participants,omitempty"`
	Timestamp          int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	InitiatorSignature []byte                 `protobuf:"bytes,4,opt,name=initiator_signature,json=initiatorSignature,proto3" json:"initiator_signature,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SessionStartCommand) Reset() {
	*x = SessionStartCommand{}
	mi := &file_proto_node_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionStartCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionStartCommand) ProtoMessage() {}

func (x *SessionStartCommand) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionStartCommand.ProtoReflect.Descriptor instead.
func (*SessionStartCommand) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{33}
}

func (x *SessionStartCommand) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionStartCommand) GetParticipants() []*SessionParticipant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *SessionStartCommand) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *SessionStartCommand) GetInitiatorSignature() []byte {
	if x != nil {
		return x.InitiatorSignature
	}
	return nil
}

// Участник сессии с подтверждённым ключом
type SessionParticipant struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PartyId          string                 `protobuf:"bytes,1,opt,name=party_id,json=partyId,proto3" json:"party_id,omitempty"`
	PartyIndex       int32                  `protobuf:"varint,2,opt,name=party_index,json=partyIndex,proto3" json:"party_index,omitempty"`
	SigningPublicKey string                 `protobuf:"bytes,3,opt,name=signing_public_key,json=signingPublicKey,proto3" json:"signing_public_key,omitempty"`
	Address          string                 `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SessionParticipant) Reset() {
	*x = SessionParticipant{}
	mi := &file_proto_node_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionParticipant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionParticipant) ProtoMessage() {}

func (x *SessionParticipant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_node_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionParticipant.ProtoReflect.Descriptor instead.
func (*SessionParticipant) Descriptor() ([]byte, []int) {
	return file_proto_node_proto_rawDescGZIP(), []int{34}
}

func (x *SessionParticipant) GetPartyId() string {
	if x != nil {
		return x.PartyId
	}
	return ""
}

func (x *SessionParticipant) GetPartyIndex() int32 {
	if x != nil {
		return x.PartyIndex
	}
	return 0
}

func (x *SessionParticipant) GetSigningPublicKey() string {
	if x != nil {
		return x.SigningPublicKey
	}
	return ""
}

func (x *SessionParticipant) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_proto_node_proto protoreflect.FileDescriptor

const file_proto_node_proto_rawDesc = "" +
	"\n" +
	"\x10proto/node.proto\x12\ampcnode\"\xa4\x01\n" +
	"\x0eSignedEnvelope\x12\x18\n" +
	"\apayload\x18\x01 \x01(\fR\apayload\x12&\n" +
	"\x0fsigner_party_id\x18\x02 \x01(\tR\rsignerPartyId\x12\x1c\n" +
	"\tsignature\x18\x03 \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\fR\x05nonce\"\x14\n" +
	"\x12HealthCheckRequest\"a\n" +
	"\x13HealthCheckResponse\x12\x18\n" +
	"\ahealthy\x18\x01 \x01(\bR\ahealthy\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x14\n" +
	"\x12GetNodeInfoRequest\"\x88\x02\n" +
	"\x13GetNodeInfoResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x19\n" +
	"\bparty_id\x18\x02 \x01(\tR\apartyId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x03 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12+\n" +
	"\x06status\x18\x05 \x01(\x0e2\x13.mpcnode.NodeStatusR\x06status\x12)\n" +
	"\x10supported_curves\x18\x06 \x03(\tR\x0fsupportedCurves\x12,\n" +
	"\x12signing_public_key\x18\a \x01(\tR\x10signingPublicKey\"\x94\x01\n" +
	"\x11InitKeygenRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12,\n" +
	"\aparties\x18\x02 \x03(\v2\x12.mpcnode.PartyInfoR\aparties\x12\x1c\n" +
	"\tthreshold\x18\x03 \x01(\x05R\tthreshold\x12\x14\n" +
	"\x05curve\x18\x04 \x01(\tR\x05curve\"\x8f\x01\n" +
	"\tPartyInfo\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1f\n" +
	"\vparty_index\x18\x02 \x01(\x05R\n" +
	"partyIndex\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12,\n" +
	"\x12signing_public_key\x18\x04 \x01(\tR\x10signingPublicKey\"r\n" +
	"\x12InitKeygenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x91\x02\n" +
	"\rKeygenMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"from_party\x18\x02 \x01(\tR\tfromParty\x12\x1d\n" +
	"\n" +
	"to_parties\x18\x03 \x03(\tR\ttoParties\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x05R\x05round\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12!\n" +
	"\fis_broadcast\x18\x06 \x01(\bR\visBroadcast\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\t \x01(\fR\x05nonce\"\x9b\x01\n" +
	"\x15KeygenMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12C\n" +
	"\x11outgoing_messages\x18\x03 \x03(\v2\x16.mpcnode.KeygenMessageR\x10outgoingMessages\"7\n" +
	"\x16GetKeygenResultRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xea\x01\n" +
	"\x17GetKeygenResultResponse\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12-\n" +
	"\x06result\x18\x04 \x01(\v2\x15.mpcnode.KeygenResultR\x06result\x12C\n" +
	"\x11outgoing_messages\x18\x05 \x03(\v2\x16.mpcnode.KeygenMessageR\x10outgoingMessages\"\xce\x01\n" +
	"\fKeygenResult\x12\x1d\n" +
	"\n" +
	"public_key\x18\x01 \x01(\tR\tpublicKey\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12!\n" +
	"\fpublic_share\x18\x03 \x01(\tR\vpublicShare\x12\x1f\n" +
	"\vparty_index\x18\x04 \x01(\x05R\n" +
	"partyIndex\x12\x1c\n" +
	"\tthreshold\x18\x05 \x01(\x05R\tthreshold\x12#\n" +
	"\rtotal_parties\x18\x06 \x01(\x05R\ftotalParties\"\xa0\x01\n" +
	"\x12InitSigningRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x15\n" +
	"\x06key_id\x18\x02 \x01(\tR\x05keyId\x12&\n" +
	"\x0fmessage_to_sign\x18\x03 \x01(\fR\rmessageToSign\x12,\n" +
	"\aparties\x18\x04 \x03(\v2\x12.mpcnode.PartyInfoR\aparties\"s\n" +
	"\x13InitSigningResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x92\x02\n" +
	"\x0eSigningMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"from_party\x18\x02 \x01(\tR\tfromParty\x12\x1d\n" +
	"\n" +
	"to_parties\x18\x03 \x03(\tR\ttoParties\x12\x14\n" +
	"\x05round\x18\x04 \x01(\x05R\x05round\x12\x18\n" +
	"\apayload\x18\x05 \x01(\fR\apayload\x12!\n" +
	"\fis_broadcast\x18\x06 \x01(\bR\visBroadcast\x12\x1c\n" +
	"\tsignature\x18\a \x01(\fR\tsignature\x12\x1c\n" +
	"\ttimestamp\x18\b \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05nonce\x18\t \x01(\fR\x05nonce\"\x9d\x01\n" +
	"\x16SigningMessageResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12D\n" +
	"\x11outgoing_messages\x18\x03 \x03(\v2\x17.mpcnode.SigningMessageR\x10outgoingMessages\"8\n" +
	"\x17GetSigningResultRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\xed\x01\n" +
	"\x18GetSigningResultResponse\x12\x1c\n" +
	"\tcompleted\x18\x01 \x01(\bR\tcompleted\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage\x12.\n" +
	"\x06result\x18\x04 \x01(\v2\x16.mpcnode.SigningResultR\x06result\x12D\n" +
	"\x11outgoing_messages\x18\x05 \x03(\v2\x17.mpcnode.SigningMessageR\x10outgoingMessages\"W\n" +
	"\rSigningResult\x12\x1c\n" +
	"\tsignature\x18\x01 \x01(\tR\tsignature\x12\f\n" +
	"\x01r\x18\x02 \x01(\tR\x01r\x12\f\n" +
	"\x01s\x18\x03 \x01(\tR\x01s\x12\f\n" +
	"\x01v\x18\x04 \x01(\x05R\x01v\"\xa7\x02\n" +
	"\x10MPCStreamMessage\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"from_party\x18\x02 \x01(\tR\tfromParty\x12\x1d\n" +
	"\n" +
	"to_parties\x18\x03 \x03(\tR\ttoParties\x126\n" +
	"\x06keygen\x18\x04 \x01(\v2\x1c.mpcnode.KeygenStreamPayloadH\x00R\x06keygen\x129\n" +
	"\asigning\x18\x05 \x01(\v2\x1d.mpcnode.SigningStreamPayloadH\x00R\asigning\x123\n" +
	"\acontrol\x18\x06 \x01(\v2\x17.mpcnode.ControlMessageH\x00R\acontrolB\x0e\n" +
	"\fmessage_type\"b\n" +
	"\x13KeygenStreamPayload\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fis_broadcast\x18\x03 \x01(\bR\visBroadcast\"c\n" +
	"\x14SigningStreamPayload\x12\x14\n" +
	"\x05round\x18\x01 \x01(\x05R\x05round\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12!\n" +
	"\fis_broadcast\x18\x03 \x01(\bR\visBroadcast\"T\n" +
	"\x0eControlMessage\x12(\n" +
	"\x04type\x18\x01 \x01(\x0e2\x14.mpcnode.ControlTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\tR\apayload\"\x9b\x01\n" +
	"\x14SignedKeygenResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12D\n" +
	"\x11outgoing_messages\x18\x03 \x03(\v2\x17.mpcnode.SignedEnvelopeR\x10outgoingMessages\"\x9c\x01\n" +
	"\x15SignedSigningResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12D\n" +
	"\x11outgoing_messages\x18\x03 \x03(\v2\x17.mpcnode.SignedEnvelopeR\x10outgoingMessages\"q\n" +
	"\x0fPeerInfoRequest\x12,\n" +
	"\x12requester_party_id\x18\x01 \x01(\tR\x10requesterPartyId\x120\n" +
	"\x14requester_public_key\x18\x02 \x01(\tR\x12requesterPublicKey\"\xab\x01\n" +
	"\x10PeerInfoResponse\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12,\n" +
	"\x12signing_public_key\x18\x02 \x01(\tR\x10signingPublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x124\n" +
	"\vknown_peers\x18\x04 \x03(\v2\x13.mpcnode.PeerRecordR\n" +
	"knownPeers\"\x8c\x01\n" +
	"\n" +
	"PeerRecord\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12,\n" +
	"\x12signing_public_key\x18\x02 \x01(\tR\x10signingPublicKey\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x1b\n" +
	"\tlast_seen\x18\x04 \x01(\x03R\blastSeen\"O\n" +
	"\vPingRequest\x12\"\n" +
	"\rfrom_party_id\x18\x01 \x01(\tR\vfromPartyId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\"a\n" +
	"\fPingResponse\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x12\x18\n" +
	"\ahealthy\x18\x03 \x01(\bR\ahealthy\"\x90\x03\n" +
	"\x12SessionInitRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x127\n" +
	"\fsession_type\x18\x02 \x01(\x0e2\x14.mpcnode.SessionTypeR\vsessionType\x122\n" +
	"\x15participant_party_ids\x18\x03 \x03(\tR\x13participantPartyIds\x12\x1c\n" +
	"\tthreshold\x18\x04 \x01(\x05R\tthreshold\x12,\n" +
	"\x12initiator_party_id\x18\x05 \x01(\tR\x10initiatorPartyId\x12/\n" +
	"\x13initiator_signature\x18\x06 \x01(\fR\x12initiatorSignature\x12\x1c\n" +
	"\ttimestamp\x18\a \x01(\x03R\ttimestamp\x12\x14\n" +
	"\x05curve\x18\b \x01(\tR\x05curve\x12&\n" +
	"\x0fmessage_to_sign\x18\t \x01(\fR\rmessageToSign\x12\x15\n" +
	"\x06key_id\x18\n" +
	" \x01(\tR\x05keyId\"\x8f\x01\n" +
	"\x13SessionInitResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12#\n" +
	"\rerror_message\x18\x02 \x01(\tR\ferrorMessage\x12\x19\n" +
	"\bparty_id\x18\x03 \x01(\tR\apartyId\x12\x1c\n" +
	"\tsignature\x18\x04 \x01(\fR\tsignature\"\xc4\x01\n" +
	"\x13SessionStartCommand\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12?\n" +
	"\fparticipants\x18\x02 \x03(\v2\x1b.mpcnode.SessionParticipantR\fparticipants\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\x12/\n" +
	"\x13initiator_signature\x18\x04 \x01(\fR\x12initiatorSignature\"\x98\x01\n" +
	"\x12SessionParticipant\x12\x19\n" +
	"\bparty_id\x18\x01 \x01(\tR\apartyId\x12\x1f\n" +
	"\vparty_index\x18\x02 \x01(\x05R\n" +
	"partyIndex\x12,\n" +
	"\x12signing_public_key\x18\x03 \x01(\tR\x10signingPublicKey\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress*\x87\x01\n" +
	"\n" +
	"NodeStatus\x12\x1b\n" +
	"\x17NODE_STATUS_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12NODE_STATUS_ONLINE\x10\x01\x12\x17\n" +
	"\x13NODE_STATUS_OFFLINE\x10\x02\x12\x14\n" +
	"\x10NODE_STATUS_BUSY\x10\x03\x12\x15\n" +
	"\x11NODE_STATUS_ERROR\x10\x04*\x9d\x01\n" +
	"\vControlType\x12\x1c\n" +
	"\x18CONTROL_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aCONTROL_TYPE_SESSION_START\x10\x01\x12\x1c\n" +
	"\x18CONTROL_TYPE_SESSION_END\x10\x02\x12\x16\n" +
	"\x12CONTROL_TYPE_ERROR\x10\x03\x12\x1a\n" +
	"\x16CONTROL_TYPE_HEARTBEAT\x10\x04*z\n" +
	"\vSessionType\x12\x1c\n" +
	"\x18SESSION_TYPE_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13SESSION_TYPE_KEYGEN\x10\x01\x12\x18\n" +
	"\x14SESSION_TYPE_SIGNING\x10\x02\x12\x1a\n" +
	"\x16SESSION_TYPE_RESHARING\x10\x032\x81\b\n" +
	"\x0eMPCNodeService\x12H\n" +
	"\vHealthCheck\x12\x1b.mpcnode.HealthCheckRequest\x1a\x1c.mpcnode.HealthCheckResponse\x12H\n" +
	"\vGetNodeInfo\x12\x1b.mpcnode.GetNodeInfoRequest\x1a\x1c.mpcnode.GetNodeInfoResponse\x12E\n" +
	"\n" +
	"InitKeygen\x12\x1a.mpcnode.InitKeygenRequest\x1a\x1b.mpcnode.InitKeygenResponse\x12N\n" +
	"\x14ProcessKeygenMessage\x12\x16.mpcnode.KeygenMessage\x1a\x1e.mpcnode.KeygenMessageResponse\x12T\n" +
	"\x0fGetKeygenResult\x12\x1f.mpcnode.GetKeygenResultRequest\x1a .mpcnode.GetKeygenResultResponse\x12H\n" +
	"\vInitSigning\x12\x1b.mpcnode.InitSigningRequest\x1a\x1c.mpcnode.InitSigningResponse\x12Q\n" +
	"\x15ProcessSigningMessage\x12\x17.mpcnode.SigningMessage\x1a\x1f.mpcnode.SigningMessageResponse\x12W\n" +
	"\x10GetSigningResult\x12 .mpcnode.GetSigningResultRequest\x1a!.mpcnode.GetSigningResultResponse\x12L\n" +
	"\x10MPCMessageStream\x12\x19.mpcnode.MPCStreamMessage\x1a\x19.mpcnode.MPCStreamMessage(\x010\x01\x12T\n" +
	"\x1aProcessSignedKeygenMessage\x12\x17.mpcnode.SignedEnvelope\x1a\x1d.mpcnode.SignedKeygenResponse\x12V\n" +
	"\x1bProcessSignedSigningMessage\x12\x17.mpcnode.SignedEnvelope\x1a\x1e.mpcnode.SignedSigningResponse\x12G\n" +
	"\x10ExchangePeerInfo\x12\x18.mpcnode.PeerInfoRequest\x1a\x19.mpcnode.PeerInfoResponse\x123\n" +
	"\x04Ping\x12\x14.mpcnode.PingRequest\x1a\x15.mpcnode.PingResponseB\x1fZ\x1dgithub.com/mpc_hsm/node/protob\x06proto3"

var (
	file_proto_node_proto_rawDescOnce sync.Once
	file_proto_node_proto_rawDescData []byte
)

func file_proto_node_proto_rawDescGZIP() []byte {
	file_proto_node_proto_rawDescOnce.Do(func() {
		file_proto_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)))
	})
	return file_proto_node_proto_rawDescData
}

var file_proto_node_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_proto_node_proto_msgTypes = make([]protoimpl.MessageInfo, 35)
var file_proto_node_proto_goTypes = []any{
	(NodeStatus)(0),                  // 0: mpcnode.NodeStatus
	(ControlType)(0),                 // 1: mpcnode.ControlType
	(SessionType)(0),                 // 2: mpcnode.SessionType
	(*SignedEnvelope)(nil),           // 3: mpcnode.SignedEnvelope
	(*HealthCheckRequest)(nil),       // 4: mpcnode.HealthCheckRequest
	(*HealthCheckResponse)(nil),      // 5: mpcnode.HealthCheckResponse
	(*GetNodeInfoRequest)(nil),       // 6: mpcnode.GetNodeInfoRequest
	(*GetNodeInfoResponse)(nil),      // 7: mpcnode.GetNodeInfoResponse
	(*InitKeygenRequest)(nil),        // 8: mpcnode.InitKeygenRequest
	(*PartyInfo)(nil),                // 9: mpcnode.PartyInfo
	(*InitKeygenResponse)(nil),       // 10: mpcnode.InitKeygenResponse
	(*KeygenMessage)(nil),            // 11: mpcnode.KeygenMessage
	(*KeygenMessageResponse)(nil),    // 12: mpcnode.KeygenMessageResponse
	(*GetKeygenResultRequest)(nil),   // 13: mpcnode.GetKeygenResultRequest
	(*GetKeygenResultResponse)(nil),  // 14: mpcnode.GetKeygenResultResponse
	(*KeygenResult)(nil),             // 15: mpcnode.KeygenResult
	(*InitSigningRequest)(nil),       // 16: mpcnode.InitSigningRequest
	(*InitSigningResponse)(nil),      // 17: mpcnode.InitSigningResponse
	(*SigningMessage)(nil),           // 18: mpcnode.SigningMessage
	(*SigningMessageResponse)(nil),   // 19: mpcnode.SigningMessageResponse
	(*GetSigningResultRequest)(nil),  // 20: mpcnode.GetSigningResultRequest
	(*GetSigningResultResponse)(nil), // 21: mpcnode.GetSigningResultResponse
	(*SigningResult)(nil),            // 22: mpcnode.SigningResult
	(*MPCStreamMessage)(nil),         // 23: mpcnode.MPCStreamMessage
	(*KeygenStreamPayload)(nil),      // 24: mpcnode.KeygenStreamPayload
	(*SigningStreamPayload)(nil),     // 25: mpcnode.SigningStreamPayload
	(*ControlMessage)(nil),           // 26: mpcnode.ControlMessage
	(*SignedKeygenResponse)(nil),     // 27: mpcnode.SignedKeygenResponse
	(*SignedSigningResponse)(nil),    // 28: mpcnode.SignedSigningResponse
	(*PeerInfoRequest)(nil),          // 29: mpcnode.PeerInfoRequest
	(*PeerInfoResponse)(nil),         // 30: mpcnode.PeerInfoResponse
	(*PeerRecord)(nil),               // 31: mpcnode.PeerRecord
	(*PingRequest)(nil),              // 32: mpcnode.PingRequest
	(*PingResponse)(nil),             // 33: mpcnode.PingResponse
	(*SessionInitRequest)(nil),       // 34: mpcnode.SessionInitRequest
	(*SessionInitResponse)(nil),      // 35: mpcnode.SessionInitResponse
	(*SessionStartCommand)(nil),      // 36: mpcnode.SessionStartCommand
	(*SessionParticipant)(nil),       // 37: mpcnode.SessionParticipant
}
var file_proto_node_proto_depIdxs = []int32{
	0,  // 0: mpcnode.GetNodeInfoResponse.status:type_name -> mpcnode.NodeStatus
	9,  // 1: mpcnode.InitKeygenRequest.parties:type_name -> mpcnode.PartyInfo
	11, // 2: mpcnode.KeygenMessageResponse.outgoing_messages:type_name -> mpcnode.KeygenMessage
	15, // 3: mpcnode.GetKeygenResultResponse.result:type_name -> mpcnode.KeygenResult
	11, // 4: mpcnode.GetKeygenResultResponse.outgoing_messages:type_name -> mpcnode.KeygenMessage
	9,  // 5: mpcnode.InitSigningRequest.parties:type_name -> mpcnode.PartyInfo
	18, // 6: mpcnode.SigningMessageResponse.outgoing_messages:type_name -> mpcnode.SigningMessage
	22, // 7: mpcnode.GetSigningResultResponse.result:type_name -> mpcnode.SigningResult
	18, // 8: mpcnode.GetSigningResultResponse.outgoing_messages:type_name -> mpcnode.SigningMessage
	24, // 9: mpcnode.MPCStreamMessage.keygen:type_name -> mpcnode.KeygenStreamPayload
	25, // 10: mpcnode.MPCStreamMessage.signing:type_name -> mpcnode.SigningStreamPayload
	26, // 11: mpcnode.MPCStreamMessage.control:type_name -> mpcnode.ControlMessage
	1,  // 12: mpcnode.ControlMessage.type:type_name -> mpcnode.ControlType
	3,  // 13: mpcnode.SignedKeygenResponse.outgoing_messages:type_name -> mpcnode.SignedEnvelope
	3,  // 14: mpcnode.SignedSigningResponse.outgoing_messages:type_name -> mpcnode.SignedEnvelope
	31, // 15: mpcnode.PeerInfoResponse.known_peers:type_name -> mpcnode.PeerRecord
	2,  // 16: mpcnode.SessionInitRequest.session_type:type_name -> mpcnode.SessionType
	37, // 17: mpcnode.SessionStartCommand.participants:type_name -> mpcnode.SessionParticipant
	4,  // 18: mpcnode.MPCNodeService.HealthCheck:input_type -> mpcnode.HealthCheckRequest
	6,  // 19: mpcnode.MPCNodeService.GetNodeInfo:input_type -> mpcnode.GetNodeInfoRequest
	8,  // 20: mpcnode.MPCNodeService.InitKeygen:input_type -> mpcnode.InitKeygenRequest
	11, // 21: mpcnode.MPCNodeService.ProcessKeygenMessage:input_type -> mpcnode.KeygenMessage
	13, // 22: mpcnode.MPCNodeService.GetKeygenResult:input_type -> mpcnode.GetKeygenResultRequest
	16, // 23: mpcnode.MPCNodeService.InitSigning:input_type -> mpcnode.InitSigningRequest
	18, // 24: mpcnode.MPCNodeService.ProcessSigningMessage:input_type -> mpcnode.SigningMessage
	20, // 25: mpcnode.MPCNodeService.GetSigningResult:input_type -> mpcnode.GetSigningResultRequest
	23, // 26: mpcnode.MPCNodeService.MPCMessageStream:input_type -> mpcnode.MPCStreamMessage
	3,  // 27: mpcnode.MPCNodeService.ProcessSignedKeygenMessage:input_type -> mpcnode.SignedEnvelope
	3,  // 28: mpcnode.MPCNodeService.ProcessSignedSigningMessage:input_type -> mpcnode.SignedEnvelope
	29, // 29: mpcnode.MPCNodeService.ExchangePeerInfo:input_type -> mpcnode.PeerInfoRequest
	32, // 30: mpcnode.MPCNodeService.Ping:input_type -> mpcnode.PingRequest
	5,  // 31: mpcnode.MPCNodeService.HealthCheck:output_type -> mpcnode.HealthCheckResponse
	7,  // 32: mpcnode.MPCNodeService.GetNodeInfo:output_type -> mpcnode.GetNodeInfoResponse
	10, // 33: mpcnode.MPCNodeService.InitKeygen:output_type -> mpcnode.InitKeygenResponse
	12, // 34: mpcnode.MPCNodeService.ProcessKeygenMessage:output_type -> mpcnode.KeygenMessageResponse
	14, // 35: mpcnode.MPCNodeService.GetKeygenResult:output_type -> mpcnode.GetKeygenResultResponse
	17, // 36: mpcnode.MPCNodeService.InitSigning:output_type -> mpcnode.InitSigningResponse
	19, // 37: mpcnode.MPCNodeService.ProcessSigningMessage:output_type -> mpcnode.SigningMessageResponse
	21, // 38: mpcnode.MPCNodeService.GetSigningResult:output_type -> mpcnode.GetSigningResultResponse
	23, // 39: mpcnode.MPCNodeService.MPCMessageStream:output_type -> mpcnode.MPCStreamMessage
	27, // 40: mpcnode.MPCNodeService.ProcessSignedKeygenMessage:output_type -> mpcnode.SignedKeygenResponse
	28, // 41: mpcnode.MPCNodeService.ProcessSignedSigningMessage:output_type -> mpcnode.SignedSigningResponse
	30, // 42: mpcnode.MPCNodeService.ExchangePeerInfo:output_type -> mpcnode.PeerInfoResponse
	33, // 43: mpcnode.MPCNodeService.Ping:output_type -> mpcnode.PingResponse
	31, // [31:44] is the sub-list for method output_type
	18, // [18:31] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_proto_node_proto_init() }
func file_proto_node_proto_init() {
	if File_proto_node_proto != nil {
		return
	}
	file_proto_node_proto_msgTypes[20].OneofWrappers = []any{
		(*MPCStreamMessage_Keygen)(nil),
		(*MPCStreamMessage_Signing)(nil),
		(*MPCStreamMessage_Control)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_node_proto_rawDesc), len(file_proto_node_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   35,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_node_proto_goTypes,
		DependencyIndexes: file_proto_node_proto_depIdxs,
		EnumInfos:         file_proto_node_proto_enumTypes,
		MessageInfos:      file_proto_node_proto_msgTypes,
	}.Build()
	File_proto_node_proto = out.File
	file_proto_node_proto_goTypes = nil
	file_proto_node_proto_depIdxs = nil
}
