// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: proto/node.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MPCNodeService_HealthCheck_FullMethodName           = "/mpcnode.MPCNodeService/HealthCheck"
	MPCNodeService_GetNodeInfo_FullMethodName           = "/mpcnode.MPCNodeService/GetNodeInfo"
	MPCNodeService_InitKeygen_FullMethodName            = "/mpcnode.MPCNodeService/InitKeygen"
	MPCNodeService_ProcessKeygenMessage_FullMethodName  = "/mpcnode.MPCNodeService/ProcessKeygenMessage"
	MPCNodeService_GetKeygenResult_FullMethodName       = "/mpcnode.MPCNodeService/GetKeygenResult"
	MPCNodeService_InitSigning_FullMethodName           = "/mpcnode.MPCNodeService/InitSigning"
	MPCNodeService_ProcessSigningMessage_FullMethodName = "/mpcnode.MPCNodeService/ProcessSigningMessage"
	MPCNodeService_GetSigningResult_FullMethodName      = "/mpcnode.MPCNodeService/GetSigningResult"
	MPCNodeService_MPCMessageStream_FullMethodName      = "/mpcnode.MPCNodeService/MPCMessageStream"
)

// MPCNodeServiceClient is the client API for MPCNodeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// MPC Node Service - основной сервис для MPC операций
type MPCNodeServiceClient interface {
	// Проверка состояния ноды
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	// Получение информации о ноде
	GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error)
	// Инициализация сессии генерации ключей
	InitKeygen(ctx context.Context, in *InitKeygenRequest, opts ...grpc.CallOption) (*InitKeygenResponse, error)
	// Обработка сообщения раунда keygen
	ProcessKeygenMessage(ctx context.Context, in *KeygenMessage, opts ...grpc.CallOption) (*KeygenMessageResponse, error)
	// Получение результата генерации ключей
	GetKeygenResult(ctx context.Context, in *GetKeygenResultRequest, opts ...grpc.CallOption) (*GetKeygenResultResponse, error)
	// Инициализация сессии подписания
	InitSigning(ctx context.Context, in *InitSigningRequest, opts ...grpc.CallOption) (*InitSigningResponse, error)
	// Обработка сообщения раунда подписания
	ProcessSigningMessage(ctx context.Context, in *SigningMessage, opts ...grpc.CallOption) (*SigningMessageResponse, error)
	// Получение результата подписания
	GetSigningResult(ctx context.Context, in *GetSigningResultRequest, opts ...grpc.CallOption) (*GetSigningResultResponse, error)
	// Двунаправленный поток для обмена MPC сообщениями
	MPCMessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MPCStreamMessage, MPCStreamMessage], error)
}

type mPCNodeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMPCNodeServiceClient(cc grpc.ClientConnInterface) MPCNodeServiceClient {
	return &mPCNodeServiceClient{cc}
}

func (c *mPCNodeServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) GetNodeInfo(ctx context.Context, in *GetNodeInfoRequest, opts ...grpc.CallOption) (*GetNodeInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeInfoResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_GetNodeInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) InitKeygen(ctx context.Context, in *InitKeygenRequest, opts ...grpc.CallOption) (*InitKeygenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitKeygenResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_InitKeygen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) ProcessKeygenMessage(ctx context.Context, in *KeygenMessage, opts ...grpc.CallOption) (*KeygenMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeygenMessageResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_ProcessKeygenMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) GetKeygenResult(ctx context.Context, in *GetKeygenResultRequest, opts ...grpc.CallOption) (*GetKeygenResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeygenResultResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_GetKeygenResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) InitSigning(ctx context.Context, in *InitSigningRequest, opts ...grpc.CallOption) (*InitSigningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitSigningResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_InitSigning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) ProcessSigningMessage(ctx context.Context, in *SigningMessage, opts ...grpc.CallOption) (*SigningMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SigningMessageResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_ProcessSigningMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) GetSigningResult(ctx context.Context, in *GetSigningResultRequest, opts ...grpc.CallOption) (*GetSigningResultResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSigningResultResponse)
	err := c.cc.Invoke(ctx, MPCNodeService_GetSigningResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mPCNodeServiceClient) MPCMessageStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[MPCStreamMessage, MPCStreamMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MPCNodeService_ServiceDesc.Streams[0], MPCNodeService_MPCMessageStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MPCStreamMessage, MPCStreamMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPCNodeService_MPCMessageStreamClient = grpc.BidiStreamingClient[MPCStreamMessage, MPCStreamMessage]

// MPCNodeServiceServer is the server API for MPCNodeService service.
// All implementations must embed UnimplementedMPCNodeServiceServer
// for forward compatibility.
//
// MPC Node Service - основной сервис для MPC операций
type MPCNodeServiceServer interface {
	// Проверка состояния ноды
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	// Получение информации о ноде
	GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error)
	// Инициализация сессии генерации ключей
	InitKeygen(context.Context, *InitKeygenRequest) (*InitKeygenResponse, error)
	// Обработка сообщения раунда keygen
	ProcessKeygenMessage(context.Context, *KeygenMessage) (*KeygenMessageResponse, error)
	// Получение результата генерации ключей
	GetKeygenResult(context.Context, *GetKeygenResultRequest) (*GetKeygenResultResponse, error)
	// Инициализация сессии подписания
	InitSigning(context.Context, *InitSigningRequest) (*InitSigningResponse, error)
	// Обработка сообщения раунда подписания
	ProcessSigningMessage(context.Context, *SigningMessage) (*SigningMessageResponse, error)
	// Получение результата подписания
	GetSigningResult(context.Context, *GetSigningResultRequest) (*GetSigningResultResponse, error)
	// Двунаправленный поток для обмена MPC сообщениями
	MPCMessageStream(grpc.BidiStreamingServer[MPCStreamMessage, MPCStreamMessage]) error
	mustEmbedUnimplementedMPCNodeServiceServer()
}

// UnimplementedMPCNodeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMPCNodeServiceServer struct{}

func (UnimplementedMPCNodeServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMPCNodeServiceServer) GetNodeInfo(context.Context, *GetNodeInfoRequest) (*GetNodeInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNodeInfo not implemented")
}
func (UnimplementedMPCNodeServiceServer) InitKeygen(context.Context, *InitKeygenRequest) (*InitKeygenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitKeygen not implemented")
}
func (UnimplementedMPCNodeServiceServer) ProcessKeygenMessage(context.Context, *KeygenMessage) (*KeygenMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessKeygenMessage not implemented")
}
func (UnimplementedMPCNodeServiceServer) GetKeygenResult(context.Context, *GetKeygenResultRequest) (*GetKeygenResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeygenResult not implemented")
}
func (UnimplementedMPCNodeServiceServer) InitSigning(context.Context, *InitSigningRequest) (*InitSigningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitSigning not implemented")
}
func (UnimplementedMPCNodeServiceServer) ProcessSigningMessage(context.Context, *SigningMessage) (*SigningMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProcessSigningMessage not implemented")
}
func (UnimplementedMPCNodeServiceServer) GetSigningResult(context.Context, *GetSigningResultRequest) (*GetSigningResultResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSigningResult not implemented")
}
func (UnimplementedMPCNodeServiceServer) MPCMessageStream(grpc.BidiStreamingServer[MPCStreamMessage, MPCStreamMessage]) error {
	return status.Errorf(codes.Unimplemented, "method MPCMessageStream not implemented")
}
func (UnimplementedMPCNodeServiceServer) mustEmbedUnimplementedMPCNodeServiceServer() {}
func (UnimplementedMPCNodeServiceServer) testEmbeddedByValue()                        {}

// UnsafeMPCNodeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MPCNodeServiceServer will
// result in compilation errors.
type UnsafeMPCNodeServiceServer interface {
	mustEmbedUnimplementedMPCNodeServiceServer()
}

func RegisterMPCNodeServiceServer(s grpc.ServiceRegistrar, srv MPCNodeServiceServer) {
	// If the following call pancis, it indicates UnimplementedMPCNodeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MPCNodeService_ServiceDesc, srv)
}

func _MPCNodeService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_GetNodeInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).GetNodeInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_GetNodeInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).GetNodeInfo(ctx, req.(*GetNodeInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_InitKeygen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitKeygenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).InitKeygen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_InitKeygen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).InitKeygen(ctx, req.(*InitKeygenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_ProcessKeygenMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KeygenMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).ProcessKeygenMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_ProcessKeygenMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).ProcessKeygenMessage(ctx, req.(*KeygenMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_GetKeygenResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeygenResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).GetKeygenResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_GetKeygenResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).GetKeygenResult(ctx, req.(*GetKeygenResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_InitSigning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitSigningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).InitSigning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_InitSigning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).InitSigning(ctx, req.(*InitSigningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_ProcessSigningMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SigningMessage)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).ProcessSigningMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_ProcessSigningMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).ProcessSigningMessage(ctx, req.(*SigningMessage))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_GetSigningResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSigningResultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MPCNodeServiceServer).GetSigningResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MPCNodeService_GetSigningResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MPCNodeServiceServer).GetSigningResult(ctx, req.(*GetSigningResultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MPCNodeService_MPCMessageStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MPCNodeServiceServer).MPCMessageStream(&grpc.GenericServerStream[MPCStreamMessage, MPCStreamMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MPCNodeService_MPCMessageStreamServer = grpc.BidiStreamingServer[MPCStreamMessage, MPCStreamMessage]

// MPCNodeService_ServiceDesc is the grpc.ServiceDesc for MPCNodeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MPCNodeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mpcnode.MPCNodeService",
	HandlerType: (*MPCNodeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "HealthCheck",
			Handler:    _MPCNodeService_HealthCheck_Handler,
		},
		{
			MethodName: "GetNodeInfo",
			Handler:    _MPCNodeService_GetNodeInfo_Handler,
		},
		{
			MethodName: "InitKeygen",
			Handler:    _MPCNodeService_InitKeygen_Handler,
		},
		{
			MethodName: "ProcessKeygenMessage",
			Handler:    _MPCNodeService_ProcessKeygenMessage_Handler,
		},
		{
			MethodName: "GetKeygenResult",
			Handler:    _MPCNodeService_GetKeygenResult_Handler,
		},
		{
			MethodName: "InitSigning",
			Handler:    _MPCNodeService_InitSigning_Handler,
		},
		{
			MethodName: "ProcessSigningMessage",
			Handler:    _MPCNodeService_ProcessSigningMessage_Handler,
		},
		{
			MethodName: "GetSigningResult",
			Handler:    _MPCNodeService_GetSigningResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "MPCMessageStream",
			Handler:       _MPCNodeService_MPCMessageStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/node.proto",
}
